#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterCms.Module.Blog.Views.Blog.Partial
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Blog\Partial\AddNewBlogEditPermalink.cshtml"
    using BetterCms.Module.Blog.Content.Resources;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Blog\Partial\AddNewBlogEditPermalink.cshtml"
    using BetterCms.Module.Root;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Blog\Partial\AddNewBlogEditPermalink.cshtml"
    using BetterCms.Module.Root.Content.Resources;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Blog\Partial\AddNewBlogEditPermalink.cshtml"
    using BetterCms.Module.Root.Mvc;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Blog\Partial\AddNewBlogEditPermalink.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Blog/Partial/AddNewBlogEditPermalink.cshtml")]
    public partial class AddNewBlogEditPermalink : System.Web.Mvc.WebViewPage<BetterCms.Module.Blog.ViewModels.Blog.BlogPostViewModel>
    {
        public AddNewBlogEditPermalink()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<div");

WriteLiteral(" class=\"bcms-input-list-holder\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 9 "..\..\Views\Blog\Partial\AddNewBlogEditPermalink.cshtml"
Write(Html.Tooltip(BlogGlobalization.EditBlogPost_Permalink_Tooltip_Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"bcms-content-titles\"");

WriteLiteral(">");

            
            #line 10 "..\..\Views\Blog\Partial\AddNewBlogEditPermalink.cshtml"
                                Write(BlogGlobalization.EditBlogPost_Permalink);

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 11 "..\..\Views\Blog\Partial\AddNewBlogEditPermalink.cshtml"
        
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Blog\Partial\AddNewBlogEditPermalink.cshtml"
         if ((ViewContext.Controller as CmsControllerBase).SecurityService.IsAuthorized(RootModuleConstants.UserRoles.EditContent))
        {

            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteLiteral(" id=\"bcms-page-editpermalink\"");

WriteLiteral(">");

            
            #line 13 "..\..\Views\Blog\Partial\AddNewBlogEditPermalink.cshtml"
                                       Write(RootGlobalization.Button_Edit);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 14 "..\..\Views\Blog\Partial\AddNewBlogEditPermalink.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n    <div");

WriteLiteral(" class=\"bcms-editseo-urlpath\"");

WriteLiteral(" id=\"bcms-page-permalink-info\"");

WriteLiteral(">");

            
            #line 16 "..\..\Views\Blog\Partial\AddNewBlogEditPermalink.cshtml"
                                                                Write(string.IsNullOrWhiteSpace(Model.BlogUrl) ? Html.Raw("/") : new MvcHtmlString(Html.Encode(Model.BlogUrl)));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"bcms-edit-urlpath-box\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n\r\n");

WriteLiteral("    ");

            
            #line 21 "..\..\Views\Blog\Partial\AddNewBlogEditPermalink.cshtml"
Write(Html.Hidden("PagePermalinkHidden", Model.BlogUrl, new { @id = "bcms-page-permalink" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"bcms-custom-input-box\"");

WriteLiteral(" style=\"width: 395px;\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 24 "..\..\Views\Blog\Partial\AddNewBlogEditPermalink.cshtml"
   Write(Html.TextBoxFor(model => model.BlogUrl, new { @id = "bcms-page-permalink-edit", @class = "bcms-editor-field-box" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 25 "..\..\Views\Blog\Partial\AddNewBlogEditPermalink.cshtml"
   Write(Html.BcmsValidationMessageFor(f => f.BlogUrl));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 27 "..\..\Views\Blog\Partial\AddNewBlogEditPermalink.cshtml"
    
            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\Blog\Partial\AddNewBlogEditPermalink.cshtml"
     if (Model.Id != Guid.Empty)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"bcms-edit-check-field\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 30 "..\..\Views\Blog\Partial\AddNewBlogEditPermalink.cshtml"
       Write(Html.CheckBoxFor(model => model.RedirectFromOldUrl));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"bcms-edit-label\"");

WriteLiteral(">");

            
            #line 31 "..\..\Views\Blog\Partial\AddNewBlogEditPermalink.cshtml"
                                    Write(BlogGlobalization.EditBlogPost_CreatePermanentRedirectToOldUrl_Title);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"bcms-edit-check-field\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 34 "..\..\Views\Blog\Partial\AddNewBlogEditPermalink.cshtml"
       Write(Html.CheckBoxFor(model => model.UseCanonicalUrl));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"bcms-edit-label\"");

WriteLiteral(">");

            
            #line 35 "..\..\Views\Blog\Partial\AddNewBlogEditPermalink.cshtml"
                                    Write(BlogGlobalization.EditBlogPost_UseCanonicalUrl);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        </div>\r\n");

            
            #line 37 "..\..\Views\Blog\Partial\AddNewBlogEditPermalink.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"bcms-btn-small\"");

WriteLiteral(" id=\"bcms-save-permalink\"");

WriteLiteral(">");

            
            #line 38 "..\..\Views\Blog\Partial\AddNewBlogEditPermalink.cshtml"
                                                    Write(RootGlobalization.Button_Ok);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n    <div");

WriteLiteral(" class=\"bcms-btn-links-small\"");

WriteLiteral(">");

            
            #line 39 "..\..\Views\Blog\Partial\AddNewBlogEditPermalink.cshtml"
                                 Write(RootGlobalization.Button_Cancel);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
