#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/BlogWidget/GetCategories.cshtml")]
    public partial class _Views_BlogWidget_GetCategories_cshtml : System.Web.Mvc.WebViewPage<IList<BetterCms.Module.Installation.Models.Blog.CategoryItem>>
    {
        public _Views_BlogWidget_GetCategories_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("    ");

            
            #line 3 "..\..\Views\BlogWidget\GetCategories.cshtml"
      
        var blogCategory = Request.Params["blogCategory"] ?? null;
    
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"submenu\"");

WriteLiteral(">\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 194), Tuple.Create("\"", 214)
            
            #line 8 "..\..\Views\BlogWidget\GetCategories.cshtml"
, Tuple.Create(Tuple.Create("", 201), Tuple.Create<System.Object, System.Int32>(Request.Path
            
            #line default
            #line hidden
, 201), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 215), Tuple.Create("\"", 272)
            
            #line 8 "..\..\Views\BlogWidget\GetCategories.cshtml"
, Tuple.Create(Tuple.Create("", 223), Tuple.Create<System.Object, System.Int32>(blogCategory == null ? "submenu-active" : null
            
            #line default
            #line hidden
, 223), false)
);

WriteLiteral(">All</a>\r\n");

            
            #line 9 "..\..\Views\BlogWidget\GetCategories.cshtml"
        
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\BlogWidget\GetCategories.cshtml"
         foreach (var category in Model)
        {
            var active = blogCategory != null && blogCategory.ToUpper() == category.Name.ToUpper();

            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 451), Tuple.Create("\"", 499)
            
            #line 12 "..\..\Views\BlogWidget\GetCategories.cshtml"
, Tuple.Create(Tuple.Create("", 458), Tuple.Create<System.Object, System.Int32>(Request.Path
            
            #line default
            #line hidden
, 458), false)
, Tuple.Create(Tuple.Create("", 471), Tuple.Create("?blogCategory=", 471), true)
            
            #line 12 "..\..\Views\BlogWidget\GetCategories.cshtml"
, Tuple.Create(Tuple.Create("", 485), Tuple.Create<System.Object, System.Int32>(category.Name
            
            #line default
            #line hidden
, 485), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 500), Tuple.Create("\"", 542)
            
            #line 12 "..\..\Views\BlogWidget\GetCategories.cshtml"
, Tuple.Create(Tuple.Create("", 508), Tuple.Create<System.Object, System.Int32>(active ? "submenu-active": null
            
            #line default
            #line hidden
, 508), false)
);

WriteLiteral(">");

            
            #line 12 "..\..\Views\BlogWidget\GetCategories.cshtml"
                                                                                                      Write(category.Name);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 13 "..\..\Views\BlogWidget\GetCategories.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>");

        }
    }
}
#pragma warning restore 1591
