using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using BetterCms.Core.Exceptions;
using BetterCms.Core.Modules.Registration;
using BetterCms.Module.Root.ViewModels;
using BetterCms.Module.Root.ViewModels.Rendering;

using Common.Logging;

namespace BetterCms.Module.Root.Services
{
    public class DefaultRenderingService : IRenderingService
    {
        /// <summary>
        /// A current class logger.
        /// </summary>
        private static readonly ILog Log = LogManager.GetCurrentClassLogger();

        /// <summary>
        /// The modules registration.
        /// </summary>
        private readonly IModulesRegistration modulesRegistration;

        /// <summary>
        /// The CMS configuration.
        /// </summary>
        private readonly ICmsConfiguration cmsConfiguration;

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultRenderingService" /> class.
        /// </summary>
        /// <param name="modulesRegistration">The modules registration.</param>
        /// <param name="cmsConfiguration">The CMS configuration.</param>
        public DefaultRenderingService(IModulesRegistration modulesRegistration, ICmsConfiguration cmsConfiguration)
        {
            this.cmsConfiguration = cmsConfiguration;
            this.modulesRegistration = modulesRegistration;
        }

        /// <summary>
        /// Retrieves a list of registered JavaScript module includes.
        /// </summary>
        /// <returns>Enumerator of JavaScriptModuleViewModel objects.</returns>
        public IEnumerable<JavaScriptModuleInclude> GetJavaScriptIncludes()
        {
            IEnumerable<JavaScriptModuleInclude> model = Enumerable.Empty<JavaScriptModuleInclude>();

            try
            {
                var javaScriptModules = modulesRegistration.GetJavaScriptModules();

                if (javaScriptModules != null)
                {
                    model = javaScriptModules
                        .Select(
                            f => new JavaScriptModuleInclude
                            {
                                Name = f.Name,
                                IsAutoGenerated = f.IsAutoGenerated,
                                Path = f.IsAutoGenerated ? string.Format(RootModuleConstants.AutoGeneratedJsFilePathPattern, f.Name) : f.Path,
                                MinifiedPath = f.MinPath ?? f.Module.MinifiedJsPath,
                                FriendlyName = f.FriendlyName,
                                Links = new ProjectionsViewModel
                                {
                                    Projections = f.Links.OrderBy(x => x.Order)
                                },
                                Globalization = new ProjectionsViewModel
                                {
                                    Projections = f.Globalization.OrderBy(x => x.Order)
                                }
                            });
                }
            }
            catch (CmsException ex)
            {
                Log.Error("Failed to retrieve java script modules.", ex);
            }

            return model;
        }

        public IEnumerable<string> GetStyleSheetIncludes()
        {
            var includes = modulesRegistration.GetStyleSheetIncludes();

            if (cmsConfiguration.UseMinifiedResources)
            {
                return includes.Select(f => f.ContainerModule.MinifiedCssPath).Distinct();
            }

            return includes.Select(f => f.Path);
        }
    }
}