#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterCms.Module.Root.Views.Shared.Partial
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\Partial\Modal.cshtml"
    using BetterCms.Module.Root.Content.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Partial/Modal.cshtml")]
    public partial class Modal : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Modal()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<script");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(" id=\"bcms-modal-template\"");

WriteLiteral(">\r\n    <div class=\"bcms-modal bcms-layer\" spellcheck=\"true\">\r\n        <div class=" +
"\"bcms-modal-body\">\r\n            <div class=\"bcms-modal-header\">\r\n               " +
" <div class=\"bcms-modal-title\">");

            
            #line 7 "..\..\Views\Shared\Partial\Modal.cshtml"
                                         Write(RootGlobalization.Message_Loading);

            
            #line default
            #line hidden
WriteLiteral(@"</div>
                <div class=""bcms-modal-close""> </div>
            </div>
            <div class=""bcms-modal-content"">
                <div class=""bcms-loader""></div>
                <div class=""bcms-modal-content-padded"" data-bind=""stopBinding: true""></div>
            </div>
            <div class=""bcms-modal-footer"">
                <div class=""bcms-modal-footer-buttons"" style=""float: left"" data-bind=""foreach: buttons"">
                    <div data-bind=""text: title, css: css, click: click, visible: !disabled()""></div>
                </div>
                <div class=""bcms-modal-cmslogo""></div>
            </div>
        </div>
    </div>
</script>
");

        }
    }
}
#pragma warning restore 1591
