#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterCms.Module.Root.Views.Shared.Partial
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\Partial\SupportBrowser.cshtml"
    using BetterCms.Module.Root.Content.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Partial/SupportBrowser.cshtml")]
    public partial class SupportBrowser : System.Web.Mvc.WebViewPage<dynamic>
    {
        public SupportBrowser()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"bcms-msg-message-page\"");

WriteLiteral(" id=\"bcms-browser-info\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"bcms-msg-message-block\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"bcms-msg-message-top\"");

WriteLiteral(">");

            
            #line 5 "..\..\Views\Shared\Partial\SupportBrowser.cshtml"
                                     Write(Html.Raw(RootGlobalization.BrowserSupport_Outdated_IE_Message));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        <div");

WriteLiteral(" class=\"bcms-msg-message-lower\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"bcms-msg-lower-upper\"");

WriteLiteral(">");

            
            #line 7 "..\..\Views\Shared\Partial\SupportBrowser.cshtml"
                                         Write(Html.Raw(RootGlobalization.BrowserSupport_UprgradeBrowser_Message_FirstLine));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("            ");

            
            #line 8 "..\..\Views\Shared\Partial\SupportBrowser.cshtml"
       Write(Html.Raw(RootGlobalization.BrowserSupport_UprgradeBrowser_Message_SecondLine));

            
            #line default
            #line hidden
WriteLiteral("<span");

WriteLiteral(" class=\"bcms-msg-message-upgrade\"");

WriteLiteral("></span>\r\n            <div");

WriteLiteral(" class=\"bcms-msg-lower-lower\"");

WriteLiteral(">");

            
            #line 9 "..\..\Views\Shared\Partial\SupportBrowser.cshtml"
                                         Write(Html.Raw(RootGlobalization.BrowserSupport_UprgradeBrowser_Message_ThirdLine));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"bcms-msg-choose-browser\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" href=\"https://www.google.com/intl/en/chrome/browser/\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" class=\"bcms-msg-download-chrome\"");

WriteLiteral(">Chrome  </a>\r\n            <a");

WriteLiteral(" href=\"http://www.mozilla.org/en-US/firefox/new/\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" class=\"bcms-msg-download-ff\"");

WriteLiteral(">Mozilla Firefox</a>\r\n            <a");

WriteLiteral(" href=\"http://windows.microsoft.com/en-us/internet-explorer/download-ie\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" class=\"bcms-msg-download-ie\"");

WriteLiteral(">Internet Explorer</a>\r\n        </div>\r\n        <a");

WriteLiteral(" class=\'bcms-msg-message-close\'");

WriteAttribute("title", Tuple.Create(" title=\"", 1271), Tuple.Create("\"", 1341)
            
            #line 16 "..\..\Views\Shared\Partial\SupportBrowser.cshtml"
, Tuple.Create(Tuple.Create("", 1279), Tuple.Create<System.Object, System.Int32>(RootGlobalization.BrowserSupport_UprgradeBrowser_Close_Button
            
            #line default
            #line hidden
, 1279), false)
);

WriteLiteral(">");

            
            #line 16 "..\..\Views\Shared\Partial\SupportBrowser.cshtml"
                                                                                                            Write(RootGlobalization.BrowserSupport_UprgradeBrowser_Close_Button);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
