#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
    using BetterCms.Module.Pages;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
    using BetterCms.Module.Pages.Content.Resources;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
    using BetterCms.Module.Pages.Controllers;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
    using BetterCms.Module.Pages.ViewModels.Widgets;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
    using BetterCms.Module.Root.ViewModels.Category;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
    using Microsoft.Web.Mvc;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Widgets/EditServerControlWidget.cshtml")]
    public partial class _Views_Widgets_EditServerControlWidget_cshtml : System.Web.Mvc.WebViewPage<EditServerControlWidgetViewModel>
    {
        public _Views_Widgets_EditServerControlWidget_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 10 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
  
    var categoriesTemplateViewModel = new CategoryTemplateViewModel
    {
        TooltipDescription = PagesGlobalization.EditPageProperties_BasicPropertiesTab_Category_Tooltip_Description
    };

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 16 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
 if (Model == null)
{
    return;
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"bcms-tab-header bcms-js-tab-header\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"bcms-modal-frame-holder\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"bcms-tab-ui bcms-tab-item bcms-active\"");

WriteLiteral(" data-name=\"#bcms-tab-1\"");

WriteLiteral(">");

            
            #line 23 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
                                                                              Write(PagesGlobalization.EditWidget_BasicPropertiesTab_Title);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        <div");

WriteLiteral(" class=\"bcms-tab-ui bcms-tab-item\"");

WriteLiteral(" data-name=\"#bcms-tab-2\"");

WriteLiteral(">");

            
            #line 24 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
                                                                  Write(PagesGlobalization.EditWidget_OptionsTab_Title);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n    </div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"bcms-modal-frame-holder\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 29 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
Write(Html.MessagesBox("bcms-edit-widget-messages"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 30 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
Write(Html.Partial("Partial/WarnMessageAboutDraft", Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"bcms-window-tabbed-options\"");

WriteLiteral(">\r\n");

            
            #line 33 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
        
            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
         using (Html.BeginForm<WidgetsController>(c => c.EditServerControlWidget((string)null), FormMethod.Post, new { @id = "bcms-widget-form", @class = "bcms-ajax-form" }))
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" id=\"bcms-tab-1\"");

WriteLiteral(" class=\"bcms-tab-single\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"bcms-form-block-holder\"");

WriteLiteral(">\r\n                    <div>\r\n                        <div");

WriteLiteral(" class=\"bcms-input-list-holder\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"bcms-content-titles\"");

WriteLiteral(">");

            
            #line 39 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
                                                        Write(PagesGlobalization.Widget_Title_Title);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                            ");

            
            #line 40 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
                       Write(Html.Tooltip(PagesGlobalization.Widget_Title_Tooltip_Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div");

WriteLiteral(" class=\"bcms-field-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 42 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
                           Write(Html.TextBoxFor(model => model.Name, new { @class = "bcms-field-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 43 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
                           Write(Html.BcmsValidationMessageFor(m => m.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n\r\n         " +
"               <div");

WriteLiteral(" class=\"bcms-input-list-holder\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"bcms-content-titles\"");

WriteLiteral(">");

            
            #line 48 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
                                                        Write(PagesGlobalization.Widget_Url_Title);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                            ");

            
            #line 49 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
                       Write(Html.Tooltip(PagesGlobalization.Widget_Url_Tooltip_Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div");

WriteLiteral(" class=\"bcms-field-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 51 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
                           Write(Html.TextBoxFor(model => model.Url, new { @class = "bcms-field-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 52 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
                           Write(Html.BcmsValidationMessageFor(m => m.Url));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n\r\n         " +
"               <div");

WriteLiteral(" class=\"bcms-input-list-holder\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"bcms-content-titles\"");

WriteLiteral(">");

            
            #line 57 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
                                                        Write(PagesGlobalization.WidgetPreviewImageUrl_Title);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                            ");

            
            #line 58 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
                       Write(Html.Tooltip(PagesGlobalization.WidgetPreviewImageUrl_Tooltip_Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div");

WriteLiteral(" class=\"bcms-field-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 60 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
                           Write(Html.TextBoxFor(model => model.PreviewImageUrl, new { @class = "bcms-field-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 61 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
                           Write(Html.BcmsValidationMessageFor(m => m.PreviewImageUrl));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n\r\n         " +
"               <div");

WriteLiteral(" class=\"bcms-input-list-holder\"");

WriteLiteral(" data-bind=\"with: categories\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 66 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
                       Write(Html.Partial("~/Areas/bcms-root/Views/Category/CategoriesTemplate.cshtml", categoriesTemplateViewModel));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n\r\n                 " +
"   <div>\r\n                        <div");

WriteLiteral(" class=\"bcms-input-list-holder\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"bcms-content-titles\"");

WriteLiteral(">");

            
            #line 72 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
                                                        Write(PagesGlobalization.WidgetPreviewImage_Title);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                            ");

            
            #line 73 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
                       Write(Html.Tooltip(PagesGlobalization.WidgetPreviewImage_Tooltip_Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div");

WriteLiteral(" class=\"bcms-preview-module-image\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n                                    <img");

WriteLiteral(" id=\"bcms-widget-preview-image\"");

WriteAttribute("src", Tuple.Create(" src=\"", 4065), Tuple.Create("\"", 4093)
            
            #line 76 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
, Tuple.Create(Tuple.Create("", 4071), Tuple.Create<System.Object, System.Int32>(Model.PreviewImageUrl
            
            #line default
            #line hidden
, 4071), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(" />\r\n                                </div>\r\n                            </div>\r\n" +
"                        </div>\r\n                    </div>\r\n                </di" +
"v>\r\n            </div>\r\n");

            
            #line 83 "..\..\Views\Widgets\EditServerControlWidget.cshtml"


            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" id=\"bcms-tab-2\"");

WriteLiteral(" class=\"bcms-tab-single\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 85 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
           Write(Html.Partial(PagesConstants.OptionsGridTemplate));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");

            
            #line 87 "..\..\Views\Widgets\EditServerControlWidget.cshtml"

            
            
            #line default
            #line hidden
            
            #line 88 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
       Write(Html.HiddenFor(model => model.Id, new { @id = "bcmsContentId" }));

            
            #line default
            #line hidden
            
            #line 88 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
                                                                             
            
            
            #line default
            #line hidden
            
            #line 89 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
       Write(Html.HiddenFor(model => model.Version, new { @id = "bcmsContentVersion" }));

            
            #line default
            #line hidden
            
            #line 89 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
                                                                                       
            
            
            #line default
            #line hidden
            
            #line 90 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
       Write(Html.HiddenFor(modal => modal.DesirableStatus, new { @class = "bcms-content-desirable-status" }));

            
            #line default
            #line hidden
            
            #line 90 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
                                                                                                             
            
            
            #line default
            #line hidden
            
            #line 91 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
       Write(Html.HiddenFor(modal => modal.PreviewOnPageContentId, new { @class = "bcms-preview-page-content-id" }));

            
            #line default
            #line hidden
            
            #line 91 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
                                                                                                                   
            
            
            #line default
            #line hidden
            
            #line 92 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
       Write(Html.HiddenSubmit());

            
            #line default
            #line hidden
            
            #line 92 "..\..\Views\Widgets\EditServerControlWidget.cshtml"
                                
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
