#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
    using BetterCms.Module.MediaManager.Content.Resources;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
    using BetterCms.Module.Root;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
    using BetterCms.Module.Root.Content.Resources;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
    using BetterCms.Module.Root.Mvc;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Partial/MediaManagerInnerContentTemplate.cshtml")]
    public partial class _Views_Shared_Partial_MediaManagerInnerContentTemplate_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.MediaManager.ViewModels.MediaManager.MediaViewModel>
    {
        public _Views_Shared_Partial_MediaManagerInnerContentTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 8 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
  
    var canEdit = (ViewContext.Controller as CmsControllerBase).SecurityService.IsAuthorized(RootModuleConstants.UserRoles.EditContent);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"bcms-top-block-holder\"");

WriteLiteral(">\r\n");

            
            #line 13 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
    
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
     if ((ViewContext.Controller as CmsControllerBase).SecurityService.IsAuthorized(RootModuleConstants.UserRoles.EditContent))
    {

            
            #line default
            #line hidden
WriteLiteral("                    <!-- ko if: !isSearchResults() -->\r\n");

WriteLiteral("        <a");

WriteLiteral(" class=\"bcms-btn-main\"");

WriteLiteral(" data-bind=\"click: uploadMedia, text: uploadButtonTitle()\"");

WriteLiteral("></a>\r\n");

WriteLiteral("                    <!-- /ko -->\r\n");

            
            #line 18 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"bcms-top-block-inner\"");

WriteLiteral(" data-bind=\"css : { \'bcms-active-search\': searchEnabled() }\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"bcms-btn-search\"");

WriteLiteral(" data-bind=\"click: toggleSearch\"");

WriteLiteral(">");

            
            #line 21 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                                                Write(RootGlobalization.Button_Search);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        <div");

WriteLiteral(" class=\"bcms-search-block\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" id=\"bcms-search-input\"");

WriteLiteral(" name=\"MediaSearch\"");

WriteLiteral(" data-bind=\"value: gridOptions().searchQuery, valueUpdate: \'afterkeydown\', enterP" +
"ress: searchMedia, hasFocus: hasFocus, enable: searchEnabled\"");

WriteLiteral(" class=\"bcms-search-field-box bcms-js-search-box\"");

WriteLiteral(" type=\"text\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 1318), Tuple.Create("\"", 1367)
            
            #line 23 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                                                                                                                                                                                     , Tuple.Create(Tuple.Create("", 1332), Tuple.Create<System.Object, System.Int32>(RootGlobalization.WaterMark_Search
            
            #line default
            #line hidden
, 1332), false)
);

WriteLiteral(" />\r\n        </div>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"bcms-top-block-pager\"");

WriteLiteral(">\r\n        <!-- ko with: gridOptions().paging -->\r\n");

WriteLiteral("        ");

            
            #line 29 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
   Write(Html.Partial(RootModuleConstants.EditableGridPagingTemplate));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <!-- /ko -->\r\n    </div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"bcms-top-block-filters\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 35 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
Write(Html.Partial("Partial/MediaManagerFilterTemplate", Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"bcms-breadcrumbs-holder\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" data-bind=\"foreach: path().pathFolders()\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" class=\"bcms-breadcrumbs-root\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-bind=\"text: pathName(), click: openMedia.bind($data, $root)\"");

WriteLiteral("></a>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n<table");

WriteLiteral(" class=\"bcms-tables\"");

WriteLiteral(" id=\"bcms-view-container\"");

WriteLiteral(">\r\n        <thead");

WriteLiteral(" class=\"bcms-media-sorting-block\"");

WriteLiteral(">\r\n            <tr>\r\n                <th");

WriteLiteral(" style=\"width: 40px; padding: 0;\"");

WriteLiteral(">&nbsp;</th>\r\n                <th>\r\n                    <a");

WriteLiteral(" class=\"bcms-sort-arrow\"");

WriteLiteral(" data-bind=\"click: sortMedia.bind($root, \'Title\'), css: { \'bcms-sort-arrow-top\': " +
"isSortedAscending(\'Title\'), \'bcms-sort-arrow-bottom\': isSortedDescending(\'Title\'" +
") }\"");

WriteLiteral(">");

            
            #line 49 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                                                                                                                                                                                               Write(MediaGlobalization.MediaList_FileNameColumn);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n\r\n                    <a");

WriteLiteral(" class=\"bcms-sort-arrow\"");

WriteLiteral(" data-bind=\"click: sortMedia.bind($root, \'FileExtension\'), css: { \'bcms-sort-arro" +
"w-top\': isSortedAscending(\'FileExtension\'), \'bcms-sort-arrow-bottom\': isSortedDe" +
"scending(\'FileExtension\') }\"");

WriteLiteral(">");

            
            #line 51 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                                                                                                                                                                                                                       Write(MediaGlobalization.MediaList_FileTypeColumn);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                </th>\r\n                <th");

WriteLiteral(" style=\"width:40px; padding: 0;\"");

WriteLiteral(">&nbsp;</th>\r\n            </tr>\r\n        </thead>\r\n        <tbody>\r\n            <" +
"tr>\r\n                <td");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n                    <!-- ko if: !isRootFolder() && !isSearchResults() -->\r\n   " +
"                 <div");

WriteLiteral(" class=\"bcms-media-up\"");

WriteLiteral(" data-bind=\"click: openParent\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"bcms-media-name\"");

WriteLiteral(">..</div>\r\n                    </div>\r\n                    <!-- /ko -->\r\n\r\n");

            
            #line 65 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 65 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                     if ((ViewContext.Controller as CmsControllerBase).SecurityService.IsAuthorized(RootModuleConstants.UserRoles.EditContent))
                    {

            
            #line default
            #line hidden
WriteLiteral("                    <!-- ko if: !isSearchResults() -->\r\n");

WriteLiteral("                        <div");

WriteLiteral(" class=\"bcms-media-new-folder\"");

WriteLiteral(" data-bind=\"click: addNewFolder\"");

WriteLiteral(">");

            
            #line 68 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                                                                      Write(MediaGlobalization.MediaManager_NewFolder);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                    <!-- /ko -->\r\n");

            
            #line 70 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </td>\r\n            </tr>\r\n        </tbody>\r\n\r\n        <!-- ko if:" +
" showNoDataInfoDiv() -->\r\n        <tbody>\r\n            <tr>\r\n                <td" +
"");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(" class=\"bcms-nomedia-data\"");

WriteLiteral(">\r\n                    <!-- ko if: isSearchResults() -->\r\n                    <di" +
"v");

WriteLiteral(" class=\"bcms-media-content-message\"");

WriteLiteral(">\r\n                        <!-- ko text: noSearchResultFound -->\r\n               " +
"         <!-- /ko -->\r\n                    </div>\r\n                    <div");

WriteLiteral(" data-bind=\"visible: canSearchInHistory(), click: searchWithFilter.bind($data, tr" +
"ue)\"");

WriteLiteral(">");

            
            #line 84 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                                                                                         Write(MediaGlobalization.MediaManager_Search_TrySearchInHistory);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <!-- /ko -->\r\n                    <!-- ko ifnot: isSe" +
"archResults() -->\r\n                    <div");

WriteLiteral(" class=\"bcms-no-data-available\"");

WriteLiteral(">");

            
            #line 87 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                                   Write(RootGlobalization.Grid_NoDataAvailable_Message);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <!-- /ko -->\r\n                </td>\r\n            </tr" +
">\r\n        </tbody>\r\n        <!-- /ko -->\r\n\r\n        <tbody");

WriteLiteral(" data-bind=\"foreach: medias()\"");

WriteLiteral(">\r\n            <tr");

WriteLiteral(" data-bind=\"click: openMedia.bind($data, $root), clickBubble: false, css: rowClas" +
"sNames()\"");

WriteLiteral(">\r\n                <td>\r\n");

            
            #line 97 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 97 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                     if ((ViewContext.Controller as CmsControllerBase).SecurityService.IsAuthorized(RootModuleConstants.UserRoles.EditContent))
                    {

            
            #line default
            #line hidden
WriteLiteral("                    <!--  ko if: !isProcessing() && !isFailed() && !isDeleting() " +
"&& !isReadOnly() -->\r\n");

WriteLiteral("                    <div");

WriteLiteral(" class=\"bcms-action-edit\"");

WriteLiteral(" data-bind=\"click: editMedia.bind($data, $root), clickBubble: false\"");

WriteLiteral(">");

            
            #line 100 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                                                                                                 Write(RootGlobalization.Button_Edit);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                    <!-- /ko -->\r\n");

            
            #line 102 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </td>\r\n                <td>\r\n                    <div");

WriteLiteral(" class=\"bcms-media-item-info\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" data-bind=\"css: iconClassNames(), click: onIconClicked.bind($data, $root)\"");

WriteLiteral("></div>\r\n\r\n                        <!-- ko if: isImage() -->\r\n                   " +
"     <div");

WriteLiteral(" class=\"bcms-media-name\"");

WriteLiteral(" data-bind=\"text: name(), event: { mousemove: $root.movePreview, mouseleave: $roo" +
"t.hidePreview, mouseout: $root.hidePreview }\"");

WriteLiteral("></div>\r\n                        <!-- /ko -->\r\n\r\n                        <!-- ko " +
"ifnot: isImage() -->\r\n                        <div");

WriteLiteral(" class=\"bcms-media-name\"");

WriteLiteral(" data-bind=\"click: onTitleClicked.bind($data, $root)\"");

WriteLiteral(">\r\n                            <!-- ko text: name() -->\r\n                        " +
"    <!-- /ko -->\r\n                            <!--  ko if: isProcessing() -->\r\n " +
"                           <br />\r\n                            <div");

WriteLiteral(" class=\"bcms-processing-file\"");

WriteLiteral(">");

            
            #line 118 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                                         Write(MediaGlobalization.MediaManager_FileStillProcessing_Message);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                            <!-- /ko -->\r\n                            <!-" +
"-  ko if: isFailed() -->\r\n                            <br />\r\n                  " +
"          <div");

WriteLiteral(" class=\"bcms-failed-file\"");

WriteLiteral(">");

            
            #line 122 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                                     Write(MediaGlobalization.MediaManager_FailedToProcessFile_Message);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                            <!-- /ko -->\r\n                            <!-" +
"-  ko if: isDeleting() -->\r\n                            <br />\r\n                " +
"            <div");

WriteLiteral(" class=\"bcms-failed-file\"");

WriteLiteral(">");

            
            #line 126 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                                     Write(RootGlobalization.Message_Deleting);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                            <!-- /ko -->\r\n                            <!-" +
"- ko if: showParentLink($root, $data) -->\r\n                            <br />\r\n " +
"                           <div");

WriteLiteral(" class=\"bcms-parent-folder\"");

WriteLiteral(">");

            
            #line 130 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                                       Write(MediaGlobalization.MediaManager_ItemParentFolder_Prefix);

            
            #line default
            #line hidden
WriteLiteral(": <div");

WriteLiteral(" data-bind=\"click: openParent.bind($data, $root), clickBubble: false, text: paren" +
"tFolderName()\"");

WriteLiteral("></div></div>\r\n                            <!-- /ko -->\r\n                        " +
"</div>\r\n                        <!-- /ko -->\r\n                    </div>\r\n\r\n    " +
"                <div");

WriteLiteral(" class=\"bcms-media-controls\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"bcms-field-wrapper\"");

WriteLiteral(">\r\n");

            
            #line 138 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 138 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                          
                        var attributes = new Dictionary<string, object>
                            {
                                {"data-bind", "value: name, valueUpdate: 'afterkeydown', enterPress: saveMedia.bind($data, $root), escPress: cancelEditMedia.bind($data, $root), hasfocus: isActive(), event: {blur: blurMediaField.bind($data, $root)}, attr: {id: nameDomId, name: nameDomId}, click: stopEvent, clickBubble: false "},
                                {"class", "bcms-field-text"}
                            };
                        attributes = Html.MergeValidationAttributes(m => m.Name, attributes);

                    
            
            #line default
            #line hidden
            
            #line 146 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
               Write(Html.TextBoxFor(m => m.Name, attributes));

            
            #line default
            #line hidden
            
            #line 146 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                                             
                    
            
            #line default
            #line hidden
            
            #line 147 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
               Write(Html.BcmsValidationMessageFor(m => m.Name, null, new { @data_bind = "attr: {'data-valmsg-for': nameDomId}" }));

            
            #line default
            #line hidden
            
            #line 147 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                                                                                                                  
                        
            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n\r\n                    <div");

WriteLiteral(" class=\"bcms-media-buttons\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"bcms-btn-primary\"");

WriteLiteral(" data-bind=\"click: saveMedia.bind($data, $root), clickBubble: false\"");

WriteLiteral(">");

            
            #line 152 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                                                                                                     Write(RootGlobalization.Button_Save);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        <div");

WriteLiteral(" class=\"bcms-btn-cancel\"");

WriteLiteral(" data-bind=\"click: cancelEditMedia.bind($data, $root), clickBubble: false\"");

WriteLiteral(">");

            
            #line 153 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                                                                                                          Write(RootGlobalization.Button_Cancel);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    </div>\r\n                    </div>\r\n                <" +
"/td>\r\n                <td>\r\n");

            
            #line 158 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 158 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                     if ((ViewContext.Controller as CmsControllerBase).SecurityService.IsAuthorized(RootModuleConstants.UserRoles.DeleteContent))
                    {

            
            #line default
            #line hidden
WriteLiteral("                    <!--  ko if: !isProcessing() && !isDeleting() && !isReadOnly(" +
") -->\r\n");

WriteLiteral("                    <div");

WriteLiteral(" class=\"bcms-action-menu\"");

WriteLiteral(" data-bind=\"click: $parent.toggleMenu, clickBubble: false\"");

WriteLiteral(">Menu</div>\r\n");

            
            #line 162 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"bcms-layer\"");

WriteLiteral(" data-bind=\"visible: isMenuOpen\"");

WriteLiteral(" style=\"position: absolute; right: 0\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" style=\"display: inline-block\"");

WriteLiteral(">\r\n            <!--  ko if: isProcessing() -->\r\n");

WriteLiteral("            ");

            
            #line 166 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
       Write(MediaGlobalization.MediaManager_FileStillProcessing_Message);

            
            #line default
            #line hidden
WriteLiteral("\r\n            <!-- /ko -->\r\n            <!--  ko if: isDeleting() -->\r\n");

WriteLiteral("            ");

            
            #line 169 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
       Write(RootGlobalization.Message_Deleting);

            
            #line default
            #line hidden
WriteLiteral("\r\n            <!-- /ko -->\r\n            <!--  ko if: !isProcessing() && !isDeleti" +
"ng() -->\r\n            <!-- ko if: !isFailed() && !isFolder() && !isImage() && $r" +
"oot.canInsertMedia() -->\r\n            <a");

WriteLiteral(" class=\"bcms-media-content-link\"");

WriteLiteral(" data-bind=\"click: insertMedia.bind($data, $root), clickBubble: false\"");

WriteLiteral(">");

            
            #line 173 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                                                                                                Write(MediaGlobalization.MediaManager_ButtonInsertFile);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n            <!-- /ko -->\r\n            <!-- ko if: !isFailed() && isImage() " +
"&& $root.canInsertMedia() -->\r\n            <a");

WriteLiteral(" class=\"bcms-media-content-link\"");

WriteLiteral(" data-bind=\"click: insertMedia.bind($data, $root), clickBubble: false\"");

WriteLiteral(">");

            
            #line 176 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                                                                                                Write(MediaGlobalization.MediaManager_ButtonInsertImage);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n            <!-- /ko -->\r\n            <!-- ko if: !isFailed() && isImage() " +
"&& $root.canInsertMediaWithOptions() -->\r\n            <a");

WriteLiteral(" class=\"bcms-media-content-link\"");

WriteLiteral("\r\n               data-bind=\"click: insertMediaWithOptions.bind($data, $root), cli" +
"ckBubble: false\"");

WriteLiteral(">");

            
            #line 180 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                                                                           Write(MediaGlobalization.MediaManager_ButtonInsertImageWithOptions);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n            <!-- /ko -->\r\n            <!-- ko if: !isFailed() && ($root.can" +
"InsertMedia() || $root.canInsertMediaWithOptions()) -->\r\n            <div");

WriteLiteral(" class=\"bcms-settings-separator\"");

WriteLiteral("></div>\r\n            <!-- /ko -->\r\n            <!-- ko if: !isFailed() && isFolde" +
"r() -->\r\n            <a");

WriteLiteral(" class=\"bcms-media-content-link\"");

WriteLiteral(" data-bind=\"click: openMedia.bind($data, $root), clickBubble: false\"");

WriteLiteral(">");

            
            #line 186 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                                                                                              Write(RootGlobalization.Button_Open);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n            <!-- /ko -->\r\n            <!-- ko if: !isFailed() && isImage() " +
"-->\r\n            <a");

WriteLiteral(" class=\"bcms-media-content-link\"");

WriteLiteral(" data-bind=\"click: previewImage.bind($data, $root), clickBubble: false\"");

WriteLiteral(">");

            
            #line 189 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                                                                                                 Write(MediaGlobalization.MediaManager_ButtonPreviewImage);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n            <!-- /ko -->\r\n            <!-- ko if: !isReadOnly() && !isFaile" +
"d() && (isFolder() || isImage() && !publicUrl() || (");

            
            #line 191 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                                                                                 Write(canEdit ? "true" : "false");

            
            #line default
            #line hidden
WriteLiteral(" && !isFolder() && !publicUrl()) || (!isFolder() && !publicUrl())) -->\r\n         " +
"   <hr />\r\n            <!-- /ko -->\r\n");

            
            #line 194 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
            
            
            #line default
            #line hidden
            
            #line 194 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
             if (canEdit)
            {

            
            #line default
            #line hidden
WriteLiteral("        <!-- ko if: !isFailed() && !isArchived() && !isReadOnly() -->\r\n");

WriteLiteral("                <a");

WriteLiteral(" class=\"bcms-media-content-link\"");

WriteLiteral(" data-bind=\"click: archiveMedia.bind($data, $root), clickBubble: false\"");

WriteLiteral(">");

            
            #line 197 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                                                                                                     Write(MediaGlobalization.MediaManager_ButtonArchive);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

WriteLiteral("        <!-- /ko -->\r\n");

WriteLiteral("        <!-- ko if: !isFailed() && isArchived() && !isReadOnly()-->\r\n");

WriteLiteral("                <a");

WriteLiteral(" class=\"bcms-media-content-link\"");

WriteLiteral(" data-bind=\"click: unarchiveMedia.bind($data, $root), clickBubble: false\"");

WriteLiteral(">");

            
            #line 200 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                                                                                                       Write(MediaGlobalization.MediaManager_ButtonUnarchive);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

WriteLiteral("        <!-- /ko -->\r\n");

            
            #line 202 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 203 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
             if ((ViewContext.Controller as
        CmsControllerBase).SecurityService.IsAuthorized(RootModuleConstants.UserRoles.DeleteContent))
            {

            
            #line default
            #line hidden
WriteLiteral("                <a");

WriteLiteral(" class=\"bcms-media-content-link\"");

WriteLiteral("\r\n                   data-bind=\"click: deleteMedia.bind($data, $root), clickBubbl" +
"e: false, visible: !isReadOnly()\"");

WriteLiteral(">");

            
            #line 207 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                                                                                            Write(RootGlobalization.Button_Delete);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 208 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 209 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
             if (canEdit)
            {

            
            #line default
            #line hidden
WriteLiteral("        <!-- ko if: !$root.isGrid() -->\r\n");

WriteLiteral("                <a");

WriteLiteral(" class=\"bcms-media-content-link\"");

WriteLiteral("\r\n                   data-bind=\"click: renameMedia.bind($data, $root), clickBubbl" +
"e: false, visible: !isReadOnly()\"");

WriteLiteral(">");

            
            #line 213 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                                                                                            Write(RootGlobalization.Button_Rename);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

WriteLiteral("        <!-- /ko -->\r\n");

            
            #line 215 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <!-- /ko -->\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" style=\"display: inline-block\"");

WriteLiteral(">\r\n            <!-- ko if: !isFailed() && canBeDownloaded() -->\r\n            <a");

WriteLiteral(" class=\"bcms-media-content-link\"");

WriteLiteral(" data-bind=\"click: downloadMedia, clickBubble: false\"");

WriteLiteral(">");

            
            #line 221 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                                                                               Write(MediaGlobalization.MediaManager_ButtonDownload);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n            <!-- /ko -->\r\n");

            
            #line 223 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
            
            
            #line default
            #line hidden
            
            #line 223 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
             if (canEdit)
            {

            
            #line default
            #line hidden
WriteLiteral("        <!-- ko if: !isFolder() -->\r\n");

WriteLiteral("                <a");

WriteLiteral(" class=\"bcms-media-content-link\"");

WriteLiteral("\r\n                   data-bind=\"click: reuploadMedia.bind($data, $root), clickBub" +
"ble: false, visible: !isReadOnly()\"");

WriteLiteral(">");

            
            #line 227 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                                                                                              Write(MediaGlobalization.Button_Reupload);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

WriteLiteral("        <!-- /ko -->\r\n");

            
            #line 229 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <!-- ko if: (!isFolder() && ");

            
            #line 230 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                    Write(canEdit ? "true" : "false");

            
            #line default
            #line hidden
WriteLiteral(") || (!isFailed() && isImage()) -->\r\n            <div");

WriteLiteral(" class=\"bcms-settings-separator\"");

WriteLiteral("></div>\r\n            <!-- /ko -->\r\n");

            
            #line 233 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
            
            
            #line default
            #line hidden
            
            #line 233 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
             if (canEdit)
            {

            
            #line default
            #line hidden
WriteLiteral("        <!-- ko if: !isFolder() -->\r\n");

WriteLiteral("                <a");

WriteLiteral(" class=\"bcms-media-content-link\"");

WriteLiteral(" data-bind=\"click: showHistory.bind($data, $root), clickBubble: false\"");

WriteLiteral(">");

            
            #line 236 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                                                                                                    Write(MediaGlobalization.Button_ShowHistory);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

WriteLiteral("        <!-- /ko -->\r\n");

            
            #line 238 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 239 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
             if (canEdit)
            {

            
            #line default
            #line hidden
WriteLiteral("        <!-- ko if: !isFailed() && !isFolder() -->\r\n");

WriteLiteral("                <a");

WriteLiteral(" class=\"bcms-media-content-link\"");

WriteLiteral(" data-bind=\"click: editMedia.bind($data, $root), clickBubble: false\"");

WriteLiteral(">");

            
            #line 242 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                                                                                                  Write(MediaGlobalization.MediaManager_ButtonProperties);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

WriteLiteral("        <!-- /ko -->\r\n");

            
            #line 244 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n\r\n        <!-- ko if: !isFailed() && !isFolder() && publicUrl() -" +
"->\r\n        <input");

WriteLiteral(" class=\"bcms-field-text\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" readonly=\"readonly\"");

WriteLiteral("\r\n               data-bind=\"value: publicUrl(), click: selectThis.bind($data, $ro" +
"ot, $element)\"");

WriteLiteral(" />\r\n        <!-- /ko -->\r\n    </div>\r\n");

WriteLiteral("                    <!-- /ko -->\r\n");

            
            #line 253 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </td>\r\n            </tr>\r\n        </tbody>\r\n    </table>\r\n    \r\n<" +
"div");

WriteLiteral(" class=\"bcms-media-preview\"");

WriteLiteral(" id=\"bcms-media-properties-preview\"");

WriteLiteral(" data-bind=\"visible: showPropertiesPreview(), style: {top: previewItem.top(), lef" +
"t: previewItem.left()}\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"bcms-content-titles\"");

WriteLiteral(">");

            
            #line 260 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                Write(MediaGlobalization.MediaManager_ImageSize);

            
            #line default
            #line hidden
WriteLiteral(": <span");

WriteLiteral(" data-bind=\"text: previewItem.size()\"");

WriteLiteral("></span></div>\r\n    <!-- ko if: previewItem.dimensions() -->\r\n    <br/>\r\n    <div" +
" class =\"bcms-content-titles\">");

            
            #line 263 "..\..\Views\Shared\Partial\MediaManagerInnerContentTemplate.cshtml"
                                 Write(MediaGlobalization.MediaManager_ImageDimensions);

            
            #line default
            #line hidden
WriteLiteral(": <span");

WriteLiteral(" data-bind=\"text: previewItem.dimensions()\"");

WriteLiteral("></span></div>\r\n    <!-- /ko -->\r\n    <div");

WriteLiteral(" data-bind=\"style: {width: previewItem.containerWidth(), height: previewItem.cont" +
"ainerHeight()}\"");

WriteLiteral(">\r\n        <img");

WriteLiteral(" data-bind=\"attr: {src: previewItem.previewUrl(), alt: previewItem.imageAlt()}, s" +
"tyle: {width: previewItem.width(), height: previewItem.height()}\"");

WriteLiteral(" />\r\n    </div>\r\n\r\n    <img");

WriteLiteral(" data-bind=\"attr: {src: previewItem.imageUrl(), alt: previewItem.imageAlt()}, eve" +
"nt: {load:previewItem.onImageLoad}\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(" />\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
