using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;

using BetterCms.Core.Modules;
using BetterCms.Module.Root.ViewModels.Rendering;

namespace BetterCms.Module.Root.Mvc.Helpers
{
    /// <summary>
    /// Java script module helper methods.
    /// </summary>
    public static class JavaScriptModulesHelper
    {
        /// <summary>
        /// Renders the comma separated names.
        /// </summary>
        /// <param name="modules">The modules.</param>
        /// <returns>Html string of comma separated names.</returns>
        public static HtmlString RenderCommaSeparatedNames(this IEnumerable<JavaScriptModuleInclude> modules)
        {
            return new HtmlString(string.Join(", ", modules.Select(f => string.Concat("'", f.Name, "'"))));
        }

        /// <summary>
        /// Renders the comma separated friendly names.
        /// </summary>
        /// <param name="modules">The modules.</param>
        /// <returns>Html string of comma separated js friendly names.</returns>
        public static HtmlString RenderCommaSeparatedFriendlyNames(this IEnumerable<JavaScriptModuleInclude> modules)
        {
            return new HtmlString(string.Join(", ", modules.Select(f => f.FriendlyName)));
        }

        /// <summary>
        /// Renders the comma separated name and path pairs.
        /// </summary>
        /// <param name="modules">The modules.</param>        
        /// <param name="useMinifiedPaths">if set to <c>true</c> use minified paths.</param>
        /// <returns>
        /// Html string of comma separated js friendly names.
        /// </returns>
        public static HtmlString RenderCommaSeparatedNamePathPairs(this IEnumerable<JavaScriptModuleInclude> modules, bool useMinifiedPaths = false)
        {
            return new HtmlString(string.Join(", ", modules.Select(f => string.Concat("'", f.Name, "' : '", GetPathForJsInclude(f, useMinifiedPaths), "'"))));
        }

        private static string GetPathForJsInclude(JavaScriptModuleInclude jsInclude, bool useMinifiedPaths = false)
        {
            string path = useMinifiedPaths && !jsInclude.IsAutoGenerated ? RemoveJsExtension(jsInclude.MinifiedPath) : RemoveJsExtension(jsInclude.Path);
            if (jsInclude.IsAutoGenerated)
            {
               // path = path + "?v=" + DateTime.Now.Ticks;
            }

            return path.ToLowerInvariant();
        }

        private static string RemoveJsExtension(string path)
        {
            int index = path.LastIndexOf(".js", StringComparison.OrdinalIgnoreCase);
            if (index > 0)
            {                
                return path.Substring(0, index);
            }

            return path;
        }
    }
}