#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Option\EditOptionValues.cshtml"
    using BetterCms.Module.Pages.Content.Resources;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Option\EditOptionValues.cshtml"
    using BetterCms.Module.Pages.Mvc.EditableGrid;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Option\EditOptionValues.cshtml"
    using BetterCms.Module.Root;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Option\EditOptionValues.cshtml"
    using BetterCms.Module.Root.Content.Resources;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Option\EditOptionValues.cshtml"
    using BetterCms.Module.Root.Mvc.Grids;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Views\Option\EditOptionValues.cshtml"
    using BetterCms.Module.Root.ViewModels.Shared;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Option/EditOptionValues.cshtml")]
    public partial class _Views_Option_EditOptionValues_cshtml : System.Web.Mvc.WebViewPage<EditableGridViewModel>
    {
        public _Views_Option_EditOptionValues_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 8 "..\..\Views\Option\EditOptionValues.cshtml"
  
    Model.ShowSearch = false;
    Model.TopBlockClass = "bcms-top-block-holder";
    Model.AddHiddenFields = true;
    Model.SaveButtonTitle = RootGlobalization.Button_Ok;
    Model.ShowMessages = false;
    Model.TopBlockAddItemView = "~/Areas/bcms-pages/Views/Option/Partial/TopBlockAddItem.cshtml";
    Model.Columns = new List<EditableGridColumn> 
    { 
        new EditableGridColumn(PagesGlobalization.EditOptionsValues_OptionKeyColumn, null, "key")
        {
            HeaderAttributes = "style=\"width: 200px;\"", 
            HiddenFieldName = "OptionValues[{0}].OptionKey"
        }, 
        new EditableGridBooleanColumn(PagesGlobalization.EditOptionsValues_UseDefaultValueColumn, null, "useDefaultValueBinding")
        {
            HiddenFieldName = "OptionValues[{0}].UseDefaultValue", 
            CellView = "~/Areas/bcms-pages/Views/Option/Partial/UseDefaultValueCell.cshtml",
            FocusIdentifier = "hasFocus"
        }, 
        new OptionValueEditableGridColumn(PagesGlobalization.EditOptionsValues_OptionDefaultValueColumn, "defaultValueBinding", "customOptionDefaultTitleBinding")
        {
            CanBeEdited = false, 
            HeaderAttributes = "style=\"width: 160px;\""
        }, 
        new EditableGridDropDownColumn(PagesGlobalization.EditOptionsValues_OptionTypeColumn, null, "calcType")
        {
            OptionsBind = "optionTypes", 
            ValueTextBind = "typeName", 
            HeaderAttributes = "style=\"width: 100px;\"", 
            CanBeEdited = false
        }, 
        new OptionValueEditableGridColumn(PagesGlobalization.EditOptionsValues_OptionValueColumn, "valueBinding", "customOptionTitleBinding")
        {
            HeaderAttributes = "style=\"width: 200px;\"", 
            HiddenFieldName = "OptionValues[{0}].OptionValue",
            FocusIdentifier = "valueHasFocus"
            
        }, 
        new EditableGridHiddenField("type", "OptionValues[{0}].Type"), 
        new EditableGridHiddenField("customType", "OptionValues[{0}].CustomType") };

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 51 "..\..\Views\Option\EditOptionValues.cshtml"
Write(Html.Partial(RootModuleConstants.EditableGridTemplate, Model));

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
