#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterCms.Module.Users.Views.Registration
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Registration\CreateFirstUser.cshtml"
    using BetterCms.Module.Users.Content.Resources;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Registration\CreateFirstUser.cshtml"
    using Microsoft.Web.Mvc;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Registration/CreateFirstUser.cshtml")]
    public partial class CreateFirstUser : System.Web.Mvc.WebViewPage<BetterCms.Module.Users.ViewModels.Registration.CreateFirstUserViewModel>
    {
        public CreateFirstUser()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n");


WriteLiteral("\r\n");


            
            #line 6 "..\..\Views\Registration\CreateFirstUser.cshtml"
  
    Layout = "~/Areas/bcms-users/Views/Shared/PublicActionLayout.cshtml";
    ViewBag.Title = "Better CMS - Users Module Registration";


            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 11 "..\..\Views\Registration\CreateFirstUser.cshtml"
 using (Html.BeginForm())
{

            
            #line default
            #line hidden
WriteLiteral("    <h2>Create first user for the Better CMS</h2>\r\n");



WriteLiteral("    <div class=\"validation-summary-valid\" data-valmsg-summary=\"true\">\r\n        ");


            
            #line 15 "..\..\Views\Registration\CreateFirstUser.cshtml"
   Write(Html.ValidationSummary());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");



WriteLiteral("    <div>\r\n        <span class=\"bcms-title\">");


            
            #line 18 "..\..\Views\Registration\CreateFirstUser.cshtml"
                            Write(UsersGlobalization.EditUser_FirstName_Title);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        <p>\r\n            ");


            
            #line 20 "..\..\Views\Registration\CreateFirstUser.cshtml"
       Write(Html.TextBoxFor(m => m.FirstName, new { @class = "bcms-editor-field-box", @id = "firstName" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 21 "..\..\Views\Registration\CreateFirstUser.cshtml"
       Write(Html.ValidationMessageFor(m => m.FirstName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </p>\r\n    </div>\r\n");


            
            #line 24 "..\..\Views\Registration\CreateFirstUser.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n        <span class=\"bcms-title\">");


            
            #line 26 "..\..\Views\Registration\CreateFirstUser.cshtml"
                            Write(UsersGlobalization.EditUser_LastName);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        <p>\r\n            ");


            
            #line 28 "..\..\Views\Registration\CreateFirstUser.cshtml"
       Write(Html.TextBoxFor(m => m.LastName, new { @class = "bcms-editor-field-box" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 29 "..\..\Views\Registration\CreateFirstUser.cshtml"
       Write(Html.ValidationMessageFor(m => m.LastName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </p>\r\n    </div>\r\n");


            
            #line 32 "..\..\Views\Registration\CreateFirstUser.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n        <span class=\"bcms-title\">");


            
            #line 34 "..\..\Views\Registration\CreateFirstUser.cshtml"
                            Write(UsersGlobalization.EditUser_UserName_Title);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        <p>\r\n            ");


            
            #line 36 "..\..\Views\Registration\CreateFirstUser.cshtml"
       Write(Html.TextBoxFor(m => m.UserName, new { @class = "bcms-editor-field-box" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 37 "..\..\Views\Registration\CreateFirstUser.cshtml"
       Write(Html.ValidationMessageFor(m => m.UserName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </p>\r\n    </div>\r\n");


            
            #line 40 "..\..\Views\Registration\CreateFirstUser.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n        <span class=\"bcms-title\">");


            
            #line 42 "..\..\Views\Registration\CreateFirstUser.cshtml"
                            Write(UsersGlobalization.EditUser_Email_Title);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        <p>\r\n            ");


            
            #line 44 "..\..\Views\Registration\CreateFirstUser.cshtml"
       Write(Html.TextBoxFor(m => m.Email, new { @class = "bcms-editor-field-box" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 45 "..\..\Views\Registration\CreateFirstUser.cshtml"
       Write(Html.ValidationMessageFor(m => m.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </p>\r\n    </div>\r\n");


            
            #line 48 "..\..\Views\Registration\CreateFirstUser.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n        <span class=\"bcms-title\">");


            
            #line 50 "..\..\Views\Registration\CreateFirstUser.cshtml"
                            Write(UsersGlobalization.EditUser_Password_Title);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        <p>\r\n            ");


            
            #line 52 "..\..\Views\Registration\CreateFirstUser.cshtml"
       Write(Html.PasswordFor(m => m.Password, new { @class = "bcms-editor-field-box" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 53 "..\..\Views\Registration\CreateFirstUser.cshtml"
       Write(Html.ValidationMessageFor(m => m.Password));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </p>\r\n    </div>\r\n");


            
            #line 56 "..\..\Views\Registration\CreateFirstUser.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n        <span class=\"bcms-title\">");


            
            #line 58 "..\..\Views\Registration\CreateFirstUser.cshtml"
                            Write(UsersGlobalization.EditUser_RetypePassword_Title);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        <p>\r\n            ");


            
            #line 60 "..\..\Views\Registration\CreateFirstUser.cshtml"
       Write(Html.PasswordFor(m => m.RetypedPassword, new { @class = "bcms-editor-field-box" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 61 "..\..\Views\Registration\CreateFirstUser.cshtml"
       Write(Html.ValidationMessageFor(m => m.RetypedPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </p>\r\n    </div>\r\n");


            
            #line 64 "..\..\Views\Registration\CreateFirstUser.cshtml"
    
            
            #line default
            #line hidden
            
            #line 64 "..\..\Views\Registration\CreateFirstUser.cshtml"
Write(Html.SubmitButton("submit", "Save", new { @class = "bcms-btn-small" }));

            
            #line default
            #line hidden
            
            #line 64 "..\..\Views\Registration\CreateFirstUser.cshtml"
                                                                           
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<script type=\"text/javascript\">\r\n    (function() {\r\n        document.getElement" +
"ById(\'firstName\').focus();\r\n    })();    \r\n</script>");


        }
    }
}
#pragma warning restore 1591
