#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\EditableGrid\Partial\MultilineTextCell.cshtml"
    using BetterCms.Module.Root.Mvc.Grids;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditableGrid/Partial/MultilineTextCell.cshtml")]
    public partial class _Views_Shared_EditableGrid_Partial_MultilineTextCell_cshtml : System.Web.Mvc.WebViewPage<EditableGridColumn>
    {
        public _Views_Shared_EditableGrid_Partial_MultilineTextCell_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<td ");

            
            #line 4 "..\..\Views\Shared\EditableGrid\Partial\MultilineTextCell.cshtml"
Write(Html.Raw(Model.Attributes));

            
            #line default
            #line hidden
WriteLiteral(">\n    <div");

WriteLiteral(" class=\"bcms-field-wrapper\"");

WriteLiteral(">\n");

            
            #line 6 "..\..\Views\Shared\EditableGrid\Partial\MultilineTextCell.cshtml"
        
            
            #line default
            #line hidden
            
            #line 6 "..\..\Views\Shared\EditableGrid\Partial\MultilineTextCell.cshtml"
         if (Model.CanBeEdited)
        {

            
            #line default
            #line hidden
WriteLiteral("            <!-- ko if: !isActive() || (");

            
            #line 8 "..\..\Views\Shared\EditableGrid\Partial\MultilineTextCell.cshtml"
                                    Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral(".editingIsDisabled && ");

            
            #line 8 "..\..\Views\Shared\EditableGrid\Partial\MultilineTextCell.cshtml"
                                                                            Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral(".editingIsDisabled()) -->\n");

            
            #line 9 "..\..\Views\Shared\EditableGrid\Partial\MultilineTextCell.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <a");

WriteLiteral(" class=\"bcms-tables-link\"");

WriteLiteral(" data-bind=\"text: getCroppedText(");

            
            #line 10 "..\..\Views\Shared\EditableGrid\Partial\MultilineTextCell.cshtml"
                                                                Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral("())\"");

WriteLiteral("></a>\n");

            
            #line 11 "..\..\Views\Shared\EditableGrid\Partial\MultilineTextCell.cshtml"
        
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Shared\EditableGrid\Partial\MultilineTextCell.cshtml"
         if (Model.CanBeEdited)
        {

            
            #line default
            #line hidden
WriteLiteral("            <!-- /ko -->\n");

WriteLiteral("            <!-- ko if: isActive() && (!");

            
            #line 14 "..\..\Views\Shared\EditableGrid\Partial\MultilineTextCell.cshtml"
                                    Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral(".editingIsDisabled || !");

            
            #line 14 "..\..\Views\Shared\EditableGrid\Partial\MultilineTextCell.cshtml"
                                                                             Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral(".editingIsDisabled()) -->\n");

WriteLiteral("            <textarea");

WriteLiteral(" class=\"bcms-field-textarea\"");

WriteLiteral(" data-bind=\"\n                css: { \'bcms-input-validation-error\': !isNew() && ");

            
            #line 16 "..\..\Views\Shared\EditableGrid\Partial\MultilineTextCell.cshtml"
                                                              Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral(".hasError && ");

            
            #line 16 "..\..\Views\Shared\EditableGrid\Partial\MultilineTextCell.cshtml"
                                                                                             Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral(".hasError() },\n                value: ");

            
            #line 17 "..\..\Views\Shared\EditableGrid\Partial\MultilineTextCell.cshtml"
                  Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral(", \n                valueUpdate: \'afterkeydown\', \n                escPress: onCanc" +
"elEdit, \n                afterRender: initInput($element, ");

            
            #line 20 "..\..\Views\Shared\EditableGrid\Partial\MultilineTextCell.cshtml"
                                            Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral("),\n                event: {blur: onBlurField, focus: onStopEvent, click: onStopEv" +
"ent}\n");

WriteLiteral("                ");

            
            #line 22 "..\..\Views\Shared\EditableGrid\Partial\MultilineTextCell.cshtml"
            Write(!string.IsNullOrWhiteSpace(Model.CustomBinding) ? string.Format(", {0}", Model.CustomBinding) : string.Empty);

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("                ");

            
            #line 23 "..\..\Views\Shared\EditableGrid\Partial\MultilineTextCell.cshtml"
            Write(Model.AutoFocus ? ", hasfocus: isActive() && hasFocus" : string.Empty);

            
            #line default
            #line hidden
WriteLiteral(" \"");

WriteLiteral("></textarea>\n");

WriteLiteral("            <!-- ko if: !isNew() &&  ");

            
            #line 24 "..\..\Views\Shared\EditableGrid\Partial\MultilineTextCell.cshtml"
                                 Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral(".hasError && ");

            
            #line 24 "..\..\Views\Shared\EditableGrid\Partial\MultilineTextCell.cshtml"
                                                                Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral(".hasError() -->\n");

WriteLiteral("            <span");

WriteLiteral(" class=\"bcms-field-validation-error\"");

WriteLiteral(">\n                <span");

WriteLiteral(" data-bind=\"html: ");

            
            #line 26 "..\..\Views\Shared\EditableGrid\Partial\MultilineTextCell.cshtml"
                                   Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral(".validationMessage()\"");

WriteLiteral("></span>\n            </span>\n");

WriteLiteral("            <!-- /ko -->\n");

WriteLiteral("            <!-- /ko -->\n");

            
            #line 30 "..\..\Views\Shared\EditableGrid\Partial\MultilineTextCell.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\n</td>");

        }
    }
}
#pragma warning restore 1591
