#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 28 "..\..\Views\History\ServerWidgetPropertiesHistory.cshtml"
    using BetterCms.Module.Pages.Content.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/History/ServerWidgetPropertiesHistory.cshtml")]
    public partial class _Views_History_ServerWidgetPropertiesHistory_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Pages.ViewModels.History.ServerWidgetHistoryViewModel>
    {
        public _Views_History_ServerWidgetPropertiesHistory_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<div");

WriteLiteral(" class=\"bcms-form-block-holder\"");

WriteLiteral(">\r\n    <div>\r\n        <div");

WriteLiteral(" class=\"bcms-input-list-holder\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"bcms-content-titles\"");

WriteLiteral(">");

            
            #line 34 "..\..\Views\History\ServerWidgetPropertiesHistory.cshtml"
                                        Write(PagesGlobalization.Widget_Title_Title);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            <div");

WriteLiteral(" class=\"bcms-field-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 36 "..\..\Views\History\ServerWidgetPropertiesHistory.cshtml"
           Write(Html.TextBoxFor(model => model.Name, new { @readonly = "readonly", @class = "bcms-field-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"bcms-input-list-holder\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"bcms-content-titles\"");

WriteLiteral(">");

            
            #line 41 "..\..\Views\History\ServerWidgetPropertiesHistory.cshtml"
                                        Write(PagesGlobalization.Widget_Url_Title);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            <div");

WriteLiteral(" class=\"bcms-field-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 43 "..\..\Views\History\ServerWidgetPropertiesHistory.cshtml"
           Write(Html.TextBoxFor(model => model.Url, new { @readonly = "readonly", @class = "bcms-field-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"bcms-input-list-holder\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"bcms-content-titles\"");

WriteLiteral(">");

            
            #line 48 "..\..\Views\History\ServerWidgetPropertiesHistory.cshtml"
                                        Write(PagesGlobalization.WidgetPreviewImageUrl_Title);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            <div");

WriteLiteral(" class=\"bcms-field-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 50 "..\..\Views\History\ServerWidgetPropertiesHistory.cshtml"
           Write(Html.TextBoxFor(model => model.PreviewUrl, new { @readonly = "readonly", @class = "bcms-field-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n    <div>\r\n        <div");

WriteLiteral(" class=\"bcms-input-list-holder\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"bcms-content-titles\"");

WriteLiteral(">");

            
            #line 57 "..\..\Views\History\ServerWidgetPropertiesHistory.cshtml"
                                        Write(PagesGlobalization.WidgetPreviewImage_Title);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            <div");

WriteLiteral(" class=\"bcms-preview-thumb\"");

WriteLiteral(">\r\n");

            
            #line 59 "..\..\Views\History\ServerWidgetPropertiesHistory.cshtml"
                
            
            #line default
            #line hidden
            
            #line 59 "..\..\Views\History\ServerWidgetPropertiesHistory.cshtml"
                 if (!string.IsNullOrWhiteSpace(Model.PreviewUrl))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <img");

WriteLiteral(" id=\"bcms-widget-preview-image\"");

WriteAttribute("src", Tuple.Create(" src=\"", 2880), Tuple.Create("\"", 2903)
            
            #line 61 "..\..\Views\History\ServerWidgetPropertiesHistory.cshtml"
, Tuple.Create(Tuple.Create("", 2886), Tuple.Create<System.Object, System.Int32>(Model.PreviewUrl
            
            #line default
            #line hidden
, 2886), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(" />\r\n");

            
            #line 62 "..\..\Views\History\ServerWidgetPropertiesHistory.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <svg");

WriteLiteral(" class=\"bcms-grid-no-preview\"");

WriteLiteral(" width=\"50\"");

WriteLiteral(" height=\"50\"");

WriteLiteral(" viewBox=\"-205 372 50 50\"");

WriteLiteral(" enable-background=\"new -205 372 50 50\"");

WriteLiteral(">\r\n                        <g");

WriteLiteral(" fill=\"#cdcdcd\"");

WriteLiteral(">\r\n                            <path");

WriteLiteral(" d=\"m-205 422h50v-50h-50v50m2-48h46v46h-46v-46\"");

WriteLiteral(" />\r\n                            <path");

WriteLiteral(" d=\"m-164.3 406.2l1.4-1.4-11.5-11.5-7.7 7.6-3.6-3.6-11.5 11.5 1.4 1.4 10.1-10.1 1" +
"1.1 11.1 1.4-1.4-7.5-7.5 6.3-6.2 10.1 10.1\"");

WriteLiteral(" />\r\n                            <path");

WriteLiteral(" d=\"m-187.9 382.4c-2.8 0-5 2.2-5 5 0 2.8 2.2 5 5 5 2.8 0 5-2.2 5-5 0-2.8-2.2-5-5-" +
"5m0 2c1.7 0 3 1.4 3 3 0 1.7-1.3 3-3 3-1.6 0-3-1.3-3-3 0-1.7 1.3-3 3-3\"");

WriteLiteral(" />\r\n                        </g>\r\n                    </svg>\r\n");

            
            #line 72 "..\..\Views\History\ServerWidgetPropertiesHistory.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
