#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 28 "..\..\Views\GalleryWidget\List.cshtml"
    using BetterCms.Module.ImagesGallery;
    
    #line default
    #line hidden
    
    #line 29 "..\..\Views\GalleryWidget\List.cshtml"
    using BetterCms.Module.ImagesGallery.Content.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/GalleryWidget/List.cshtml")]
    public partial class _Views_GalleryWidget_List_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.ImagesGallery.ViewModels.GalleryViewModel>
    {
        public _Views_GalleryWidget_List_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 32 "..\..\Views\GalleryWidget\List.cshtml"
 if (Model.LoadCmsStyles)
{
    
            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\GalleryWidget\List.cshtml"
Write(Html.Partial("Partial/ListStyles"));

            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\GalleryWidget\List.cshtml"
                                       
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 37 "..\..\Views\GalleryWidget\List.cshtml"
  
    var i = 0;
    var l = Model.Albums.Count;
    var perSection = Model.ImagesPerSection <= 0 ? l : Model.ImagesPerSection;
    
    foreach (var album in Model.Albums)
    {
        if (i % perSection == 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("<section>\r\n");

            
            #line 47 "..\..\Views\GalleryWidget\List.cshtml"
        }
        

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"bcms-album-holder\"");

WriteLiteral(">\r\n            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1878), Tuple.Create("\"", 1904)
            
            #line 50 "..\..\Views\GalleryWidget\List.cshtml"
, Tuple.Create(Tuple.Create("", 1884), Tuple.Create<System.Object, System.Int32>(album.CoverImageUrl
            
            #line default
            #line hidden
, 1884), false)
);

WriteAttribute("alt", Tuple.Create(" alt=\"", 1905), Tuple.Create("\"", 1923)
            
            #line 50 "..\..\Views\GalleryWidget\List.cshtml"
, Tuple.Create(Tuple.Create("", 1911), Tuple.Create<System.Object, System.Int32>(album.Title
            
            #line default
            #line hidden
, 1911), false)
);

WriteLiteral(" />\r\n            <div");

WriteLiteral(" class=\"bcms-album-name\"");

WriteLiteral(">\r\n                <h4><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1994), Tuple.Create("\"", 2011)
            
            #line 52 "..\..\Views\GalleryWidget\List.cshtml"
, Tuple.Create(Tuple.Create("", 2001), Tuple.Create<System.Object, System.Int32>(album.Url
            
            #line default
            #line hidden
, 2001), false)
);

WriteLiteral(">");

            
            #line 52 "..\..\Views\GalleryWidget\List.cshtml"
                                    Write(album.Title);

            
            #line default
            #line hidden
WriteLiteral("</a></h4>\r\n                <span>");

            
            #line 53 "..\..\Views\GalleryWidget\List.cshtml"
                 Write(album.ImagesCount);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 53 "..\..\Views\GalleryWidget\List.cshtml"
                                    Write(ImagesGalleryGlobalization.GalleryWidget_Pictures);

            
            #line default
            #line hidden
            
            #line 53 "..\..\Views\GalleryWidget\List.cshtml"
                                                                                            if (album.LastUpdateDate.HasValue) { 
            
            #line default
            #line hidden
            
            #line 53 "..\..\Views\GalleryWidget\List.cshtml"
                                                                                                                            Write(Html.Raw(","));

            
            #line default
            #line hidden
            
            #line 53 "..\..\Views\GalleryWidget\List.cshtml"
                                                                                                                                                }
            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 54 "..\..\Views\GalleryWidget\List.cshtml"
                
            
            #line default
            #line hidden
            
            #line 54 "..\..\Views\GalleryWidget\List.cshtml"
                 if (album.LastUpdateDate.HasValue)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <time");

WriteAttribute("datetime", Tuple.Create(" datetime=\"", 2287), Tuple.Create("\"", 2397)
            
            #line 56 "..\..\Views\GalleryWidget\List.cshtml"
, Tuple.Create(Tuple.Create("", 2298), Tuple.Create<System.Object, System.Int32>(album.LastUpdateDate.Value.ToString(ImagesGalleryModuleConstants.GalleryWidgetUpdateDateTagFormat)
            
            #line default
            #line hidden
, 2298), false)
);

WriteLiteral(">");

            
            #line 56 "..\..\Views\GalleryWidget\List.cshtml"
                                                                                                                                    Write(album.LastUpdateDate.Value.ToString(ImagesGalleryModuleConstants.GalleryWidgetUpdateDateDisplayFormat));

            
            #line default
            #line hidden
WriteLiteral("</time>\r\n");

            
            #line 57 "..\..\Views\GalleryWidget\List.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n");

            
            #line 60 "..\..\Views\GalleryWidget\List.cshtml"

        i++;

        if (i % perSection == 0 || i == l)
        {

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("</section>\r\n");

            
            #line 66 "..\..\Views\GalleryWidget\List.cshtml"
        }
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
