#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 31 "..\..\Views\Images\ImageEditorInsert.cshtml"
    using BetterCms.Module.MediaManager.Content.Resources;
    
    #line default
    #line hidden
    
    #line 32 "..\..\Views\Images\ImageEditorInsert.cshtml"
    using BetterCms.Module.MediaManager.Controllers;
    
    #line default
    #line hidden
    
    #line 28 "..\..\Views\Images\ImageEditorInsert.cshtml"
    using BetterCms.Module.MediaManager.Models;
    
    #line default
    #line hidden
    
    #line 33 "..\..\Views\Images\ImageEditorInsert.cshtml"
    using BetterCms.Module.MediaManager.ViewModels.Images;
    
    #line default
    #line hidden
    
    #line 30 "..\..\Views\Images\ImageEditorInsert.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    #line 29 "..\..\Views\Images\ImageEditorInsert.cshtml"
    using Microsoft.Web.Mvc;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Images/ImageEditorInsert.cshtml")]
    public partial class _Views_Images_ImageEditorInsert_cshtml : System.Web.Mvc.WebViewPage<ImageViewModel>
    {
        public _Views_Images_ImageEditorInsert_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<div");

WriteLiteral(" class=\"bcms-modal-frame-holder\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 37 "..\..\Views\Images\ImageEditorInsert.cshtml"
Write(Html.MessagesBox());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"bcms-window-options\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"bcms-file-manager-inner bcms-clearfix\"");

WriteLiteral(">\r\n");

            
            #line 41 "..\..\Views\Images\ImageEditorInsert.cshtml"
            
            
            #line default
            #line hidden
            
            #line 41 "..\..\Views\Images\ImageEditorInsert.cshtml"
             using (Html.BeginForm<ImagesController>(f => f.ImageEditor((ImageViewModel)null), FormMethod.Post, new { @class = "bcms-ajax-form", @enctype = "multipart/form-data" }))
        {
            
            
            #line default
            #line hidden
            
            #line 43 "..\..\Views\Images\ImageEditorInsert.cshtml"
       Write(Html.HiddenFor(model => model.Id));

            
            #line default
            #line hidden
            
            #line 43 "..\..\Views\Images\ImageEditorInsert.cshtml"
                                              
            
            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\Images\ImageEditorInsert.cshtml"
       Write(Html.HiddenFor(model => model.Version, new { @id = "image-version-field" }));

            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\Images\ImageEditorInsert.cshtml"
                                                                                        


            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"bcms-input-list-holder\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"bcms-content-titles\"");

WriteLiteral(">");

            
            #line 47 "..\..\Views\Images\ImageEditorInsert.cshtml"
                                            Write(MediaGlobalization.ImageEditor_Dialog_SubTitle);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            </div>\r\n");

            
            #line 49 "..\..\Views\Images\ImageEditorInsert.cshtml"


            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"bcms-croped-block\"");

WriteLiteral(">\r\n                <img");

WriteLiteral(" class=\"bcms-crop-image\"");

WriteAttribute("src", Tuple.Create(" src=\"", 2380), Tuple.Create("\"", 2396)
            
            #line 51 "..\..\Views\Images\ImageEditorInsert.cshtml"
, Tuple.Create(Tuple.Create("", 2386), Tuple.Create<System.Object, System.Int32>(Model.Url
            
            #line default
            #line hidden
, 2386), false)
);

WriteLiteral(" data-id=\"");

            
            #line 51 "..\..\Views\Images\ImageEditorInsert.cshtml"
                                                                  Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-version=\"");

            
            #line 51 "..\..\Views\Images\ImageEditorInsert.cshtml"
                                                                                           Write(Model.Version);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" />\r\n            </div>\r\n");

            
            #line 53 "..\..\Views\Images\ImageEditorInsert.cshtml"


            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"bcms-edit-file-info\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"bcms-file-info-text\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"bcms-content-titles\"");

WriteLiteral(">");

            
            #line 56 "..\..\Views\Images\ImageEditorInsert.cshtml"
                                                Write(MediaGlobalization.ImageEditor_Dialog_PublicUrl);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <div");

WriteLiteral(" class=\"bcms-edit-file-info\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" class=\"bcms-field-text bcms-editor-selectable-field-box\"");

WriteLiteral(" type=\"text\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2835), Tuple.Create("\"", 2853)
            
            #line 58 "..\..\Views\Images\ImageEditorInsert.cshtml"
                           , Tuple.Create(Tuple.Create("", 2843), Tuple.Create<System.Object, System.Int32>(Model.Url
            
            #line default
            #line hidden
, 2843), false)
);

WriteLiteral(" readonly=\"readonly\"");

WriteLiteral(" />\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"bcms-input-list-holder\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"bcms-content-titles\"");

WriteLiteral(">");

            
            #line 62 "..\..\Views\Images\ImageEditorInsert.cshtml"
                                                Write(MediaGlobalization.ImageEditor_Dialog_Caption);

            
            #line default
            #line hidden
WriteLiteral(":</div>\r\n");

WriteLiteral("                    ");

            
            #line 63 "..\..\Views\Images\ImageEditorInsert.cshtml"
               Write(Html.Tooltip(MediaGlobalization.ImageEditor_Dialog_Caption_Tooltip_Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 64 "..\..\Views\Images\ImageEditorInsert.cshtml"
               Write(Html.TextBoxFor(f => f.Caption, new { @class = "bcms-field-text", @id = "Caption" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"bcms-file-info-text\"");

WriteLiteral("><b>");

            
            #line 66 "..\..\Views\Images\ImageEditorInsert.cshtml"
                                               Write(MediaGlobalization.ImageEditor_Dialog_FileName);

            
            #line default
            #line hidden
WriteLiteral(":</b> <span");

WriteLiteral(" id=\"image-file-name\"");

WriteLiteral(">");

            
            #line 66 "..\..\Views\Images\ImageEditorInsert.cshtml"
                                                                                                                               Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("</span></div>\r\n                <div");

WriteLiteral(" class=\"bcms-file-info-text\"");

WriteLiteral("><b>");

            
            #line 67 "..\..\Views\Images\ImageEditorInsert.cshtml"
                                               Write(MediaGlobalization.ImageEditor_Dialog_FileSize);

            
            #line default
            #line hidden
WriteLiteral(":</b> <span");

WriteLiteral(" id=\"image-file-size\"");

WriteLiteral(">");

            
            #line 67 "..\..\Views\Images\ImageEditorInsert.cshtml"
                                                                                                                               Write(Model.FileSize);

            
            #line default
            #line hidden
WriteLiteral("</span></div>\r\n                <div");

WriteLiteral(" class=\"bcms-file-info-text\"");

WriteLiteral(">\r\n");

            
            #line 69 "..\..\Views\Images\ImageEditorInsert.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 69 "..\..\Views\Images\ImageEditorInsert.cshtml"
                     if (Model.CroppedWidth != Model.OriginalImageWidth || Model.CroppedHeight != Model.OriginalImageHeight)
                    {

            
            #line default
            #line hidden
WriteLiteral("                <b>");

            
            #line 71 "..\..\Views\Images\ImageEditorInsert.cshtml"
              Write(MediaGlobalization.ImageEditor_Dialog_CroppedDimensions);

            
            #line default
            #line hidden
WriteLiteral(":</b>\r\n");

            
            #line 72 "..\..\Views\Images\ImageEditorInsert.cshtml"
                    }
                    else
                    {

            
            #line default
            #line hidden
WriteLiteral("                <b>");

            
            #line 75 "..\..\Views\Images\ImageEditorInsert.cshtml"
              Write(MediaGlobalization.ImageEditor_Dialog_Dimensions);

            
            #line default
            #line hidden
WriteLiteral(":</b>\r\n");

            
            #line 76 "..\..\Views\Images\ImageEditorInsert.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    <span");

WriteLiteral(" id=\"image-dimensions\"");

WriteLiteral(">");

            
            #line 77 "..\..\Views\Images\ImageEditorInsert.cshtml"
                                           Write(Model.CroppedWidth);

            
            #line default
            #line hidden
WriteLiteral(" x ");

            
            #line 77 "..\..\Views\Images\ImageEditorInsert.cshtml"
                                                                 Write(Model.CroppedHeight);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </div>\r\n            </div>\r\n");

            
            #line 80 "..\..\Views\Images\ImageEditorInsert.cshtml"


            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"bcms-file-alignment\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"bcms-content-titles\"");

WriteLiteral(">");

            
            #line 82 "..\..\Views\Images\ImageEditorInsert.cshtml"
                                            Write(MediaGlobalization.ImageEditor_Dialog_AligmentTitle);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                <div");

WriteLiteral(" class=\"bcms-alignment-controls\"");

WriteLiteral(">\r\n                    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 4479), Tuple.Create("\"", 4576)
, Tuple.Create(Tuple.Create("", 4487), Tuple.Create("bcms-align-center", 4487), true)
            
            #line 84 "..\..\Views\Images\ImageEditorInsert.cshtml"
, Tuple.Create(Tuple.Create("", 4504), Tuple.Create<System.Object, System.Int32>(Model.ImageAlign == MediaImageAlign.Center ? "-active" : string.Empty
            
            #line default
            #line hidden
, 4504), false)
);

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"radio\"");

WriteLiteral(" id=\"aligncenter\"");

WriteLiteral(" name=\"ImageAlign\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4658), Tuple.Create("\"", 4696)
            
            #line 85 "..\..\Views\Images\ImageEditorInsert.cshtml"
       , Tuple.Create(Tuple.Create("", 4666), Tuple.Create<System.Object, System.Int32>((int)MediaImageAlign.Center
            
            #line default
            #line hidden
, 4666), false)
);

WriteLiteral(" ");

            
            #line 85 "..\..\Views\Images\ImageEditorInsert.cshtml"
                                                                                                                  Write(Model.ImageAlign == MediaImageAlign.Center ? "checked" : string.Empty);

            
            #line default
            #line hidden
WriteLiteral(">\r\n                    </div>\r\n                    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 4825), Tuple.Create("\"", 4918)
, Tuple.Create(Tuple.Create("", 4833), Tuple.Create("bcms-align-left", 4833), true)
            
            #line 87 "..\..\Views\Images\ImageEditorInsert.cshtml"
, Tuple.Create(Tuple.Create("", 4848), Tuple.Create<System.Object, System.Int32>(Model.ImageAlign == MediaImageAlign.Left ? "-active" : string.Empty
            
            #line default
            #line hidden
, 4848), false)
);

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"radio\"");

WriteLiteral(" id=\"alignleft\"");

WriteLiteral(" name=\"ImageAlign\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4998), Tuple.Create("\"", 5034)
            
            #line 88 "..\..\Views\Images\ImageEditorInsert.cshtml"
     , Tuple.Create(Tuple.Create("", 5006), Tuple.Create<System.Object, System.Int32>((int)MediaImageAlign.Left
            
            #line default
            #line hidden
, 5006), false)
);

WriteLiteral(" ");

            
            #line 88 "..\..\Views\Images\ImageEditorInsert.cshtml"
                                                                                                              Write(Model.ImageAlign == MediaImageAlign.Left ? "checked" : string.Empty);

            
            #line default
            #line hidden
WriteLiteral(">\r\n                    </div>\r\n                    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 5161), Tuple.Create("\"", 5256)
, Tuple.Create(Tuple.Create("", 5169), Tuple.Create("bcms-align-right", 5169), true)
            
            #line 90 "..\..\Views\Images\ImageEditorInsert.cshtml"
, Tuple.Create(Tuple.Create("", 5185), Tuple.Create<System.Object, System.Int32>(Model.ImageAlign == MediaImageAlign.Right ? "-active" : string.Empty
            
            #line default
            #line hidden
, 5185), false)
);

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"radio\"");

WriteLiteral(" id=\"alignright\"");

WriteLiteral(" name=\"ImageAlign\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5337), Tuple.Create("\"", 5374)
            
            #line 91 "..\..\Views\Images\ImageEditorInsert.cshtml"
      , Tuple.Create(Tuple.Create("", 5345), Tuple.Create<System.Object, System.Int32>((int)MediaImageAlign.Right
            
            #line default
            #line hidden
, 5345), false)
);

WriteLiteral(" ");

            
            #line 91 "..\..\Views\Images\ImageEditorInsert.cshtml"
                                                                                                                Write(Model.ImageAlign == MediaImageAlign.Right ? "checked" : string.Empty);

            
            #line default
            #line hidden
WriteLiteral(">\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"bcms-input-list-holder\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"bcms-content-titles\"");

WriteLiteral(">");

            
            #line 95 "..\..\Views\Images\ImageEditorInsert.cshtml"
                                                Write(MediaGlobalization.ImageEditor_Dialog_Description);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                    ");

            
            #line 96 "..\..\Views\Images\ImageEditorInsert.cshtml"
               Write(Html.Tooltip(MediaGlobalization.ImageEditor_Dialog_Description_Tooltip_Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"bcms-textarea-box\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 98 "..\..\Views\Images\ImageEditorInsert.cshtml"
                   Write(Html.TextAreaFor(f => f.Description, new
                                                                  {
                                                                      @class = "bcms-field-textarea",
                                                                      @id = "Description",
                                                                      @readonly = "readonly"
                                                                  }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n");

            
            #line 107 "..\..\Views\Images\ImageEditorInsert.cshtml"

            if (Model.Tags != null && Model.Tags.Count > 0)
            {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"bcms-media-tags-box-holder bcms-clearfix\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"bcms-content-titles\"");

WriteLiteral(">");

            
            #line 111 "..\..\Views\Images\ImageEditorInsert.cshtml"
                                            Write(MediaGlobalization.ImageEditor_Dialog_Tags_Title);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                <div");

WriteLiteral(" class=\"bcms-single-tag-holder\"");

WriteLiteral(">\r\n");

            
            #line 113 "..\..\Views\Images\ImageEditorInsert.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 113 "..\..\Views\Images\ImageEditorInsert.cshtml"
                     foreach (var tag in Model.Tags)
                        {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"bcms-single-tag\"");

WriteLiteral(">");

            
            #line 115 "..\..\Views\Images\ImageEditorInsert.cshtml"
                                        Write(tag);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 116 "..\..\Views\Images\ImageEditorInsert.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n            </div>\r\n");

            
            #line 119 "..\..\Views\Images\ImageEditorInsert.cshtml"
            }
        }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
