#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterCms.Module.Users.Views.Authentication
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Authentication\Login.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Authentication\Login.cshtml"
    using BetterCms.Module.Users.Content.Resources;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Authentication\Login.cshtml"
    using Microsoft.Web.Mvc;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Authentication/Login.cshtml")]
    public partial class Login : System.Web.Mvc.WebViewPage<BetterCms.Module.Users.ViewModels.Authentication.LoginViewModel>
    {
        public Login()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Views\Authentication\Login.cshtml"
  
    Layout = "~/Areas/bcms-users/Views/Shared/PublicActionLayout.cshtml";
    ViewBag.Title = "Login";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("Head", () => {

WriteLiteral("\r\n    <style>\r\n        .bcms-body {\r\n            width: 260px;\r\n            margi" +
"n: 0 auto;\r\n            padding: 20px 0 74px;\r\n        }\r\n    </style>\r\n");

});

WriteLiteral("\r\n");

            
            #line 21 "..\..\Views\Authentication\Login.cshtml"
 using (Html.BeginForm())
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"validation-summary-valid\"");

WriteLiteral(" data-valmsg-summary=\"true\"");

WriteLiteral(">\r\n");

WriteLiteral("       ");

            
            #line 24 "..\..\Views\Authentication\Login.cshtml"
  Write(Html.TabbedContentMessagesBox());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

WriteLiteral("    <div>\r\n        <span");

WriteLiteral(" class=\"bcms-title\"");

WriteLiteral(">");

            
            #line 27 "..\..\Views\Authentication\Login.cshtml"
                            Write(UsersGlobalization.Login_UserName);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        <p>\r\n");

WriteLiteral("            ");

            
            #line 29 "..\..\Views\Authentication\Login.cshtml"
       Write(Html.TextBoxFor(m => m.UserName, new { id = "userName", @class = "bcms-editor-field-box"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 30 "..\..\Views\Authentication\Login.cshtml"
       Write(Html.ValidationMessageFor(m => m.UserName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </p>\r\n    </div>\r\n");

            
            #line 33 "..\..\Views\Authentication\Login.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n        <span");

WriteLiteral(" class=\"bcms-title\"");

WriteLiteral(">");

            
            #line 35 "..\..\Views\Authentication\Login.cshtml"
                            Write(UsersGlobalization.Login_Password);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        <p>\r\n");

WriteLiteral("            ");

            
            #line 37 "..\..\Views\Authentication\Login.cshtml"
       Write(Html.PasswordFor(m => m.Password, new { @class = "bcms-editor-field-box" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 38 "..\..\Views\Authentication\Login.cshtml"
       Write(Html.ValidationMessageFor(m => m.Password));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </p>\r\n    </div>\r\n");

WriteLiteral("    <div>\r\n        <span");

WriteLiteral(" class=\"bcms-title\"");

WriteLiteral(">&nbsp;</span>\r\n        <p>\r\n");

WriteLiteral("            ");

            
            #line 44 "..\..\Views\Authentication\Login.cshtml"
       Write(Html.CheckBoxFor(m => m.RememberMe));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 45 "..\..\Views\Authentication\Login.cshtml"
       Write(Html.LabelFor(m => m.RememberMe));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </p>\r\n    </div>\r\n");

            
            #line 48 "..\..\Views\Authentication\Login.cshtml"

    Dictionary<string, object> submitProperties = new Dictionary<string, object>();
    submitProperties.Add("class", "bcms-btn-small");
    if (!Model.IsFormsAuthenticationEnabled)
    {
        submitProperties.Add("disabled", "disabled");
    }
    
    
            
            #line default
            #line hidden
            
            #line 56 "..\..\Views\Authentication\Login.cshtml"
Write(Html.SubmitButton("submit", "Login", submitProperties));

            
            #line default
            #line hidden
            
            #line 56 "..\..\Views\Authentication\Login.cshtml"
                                                           
    
            
            #line default
            #line hidden
            
            #line 57 "..\..\Views\Authentication\Login.cshtml"
Write(Html.HiddenFor(m => m.ReturnUrl));

            
            #line default
            #line hidden
            
            #line 57 "..\..\Views\Authentication\Login.cshtml"
                                     
}

            
            #line default
            #line hidden
WriteLiteral("<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    (function() {\r\n        document.getElementById(\'userName\').focus();\r\n    }" +
")();    \r\n</script>");

        }
    }
}
#pragma warning restore 1591
