#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Category\CategoriesTemplate.cshtml"
    using BetterCms.Module.Root;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Category\CategoriesTemplate.cshtml"
    using BetterCms.Module.Root.Content.Resources;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Category\CategoriesTemplate.cshtml"
    using BetterCms.Module.Root.Mvc;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Category\CategoriesTemplate.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Category/CategoriesTemplate.cshtml")]
    public partial class _Views_Category_CategoriesTemplate_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Root.ViewModels.Category.CategoryTemplateViewModel>
    {
        public _Views_Category_CategoriesTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\n");

            
            #line 8 "..\..\Views\Category\CategoriesTemplate.cshtml"
   var canEdit = (ViewContext.Controller as CmsControllerBase).SecurityService.IsAuthorized(RootModuleConstants.UserRoles.EditContent); 
            
            #line default
            #line hidden
WriteLiteral("\n<div");

WriteLiteral(" class=\"bcms-input-list-holder\"");

WriteLiteral(">\n");

WriteLiteral("    ");

            
            #line 10 "..\..\Views\Category\CategoriesTemplate.cshtml"
Write(Html.Tooltip(Model.TooltipDescription));

            
            #line default
            #line hidden
WriteLiteral("\n\n    <div");

WriteLiteral(" class=\"bcms-content-titles\"");

WriteLiteral(">\n");

WriteLiteral("        ");

            
            #line 13 "..\..\Views\Category\CategoriesTemplate.cshtml"
   Write(RootGlobalization.CategoriesTemplate_AddCategories_Title);

            
            #line default
            #line hidden
WriteLiteral("\n        <div");

WriteLiteral(" class=\"bcms-btn-plus\"");

WriteLiteral(" data-bind=\"css: { \'bcms-btn-plus-expand\': isExpanded() }");

            
            #line 14 "..\..\Views\Category\CategoriesTemplate.cshtml"
                                                                                       Write(canEdit ? ", click: expandCollapse" : string.Empty);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">&nbsp;</div>\n\n        <div");

WriteLiteral(" class=\"bcms-tags-field-holder\"");

WriteLiteral(" data-bind=\"visible: isExpanded()\"");

WriteLiteral(">\n            <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"bcms-add-tags-field\"");

WriteLiteral(" style=\"width: 107px;\"");

WriteLiteral(@" data-bind=""
                    css: { 'bcms-tag-validation-error': newItem.hasError() },
                    value: newItem,
                    valueUpdate: 'afterkeydown',
                    hasfocus: hasfocus,
                    autocompleteList: 'onlyExisting',
                    enterPress: function(){},
                    escPress: clearItem""");

WriteLiteral(" />\n            <!-- ko if: newItem.hasError()  -->\n            <span");

WriteLiteral(" class=\"bcms-tag-field-validation-error\"");

WriteLiteral(">\n                <span");

WriteLiteral(" data-bind=\"text: newItem.validationMessage()\"");

WriteLiteral("></span>\n            </span>\n            <!-- /ko -->\n        </div>\n    </div>\n\n" +
"    <div");

WriteLiteral(" class=\"bcms-single-tag-holder\"");

WriteLiteral(" data-bind=\"foreach: items()\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"bcms-single-tag\"");

WriteLiteral(" data-bind=\"css: { \'bcms-single-tag-active\': isActive() }\"");

WriteLiteral("><span");

WriteLiteral(" data-bind=\"    text: name()\"");

WriteLiteral("></span><a");

WriteLiteral(" data-bind=\"");

            
            #line 34 "..\..\Views\Category\CategoriesTemplate.cshtml"
                                                                                                                                                   Write(canEdit ? "click: remove" : string.Empty);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">");

            
            #line 34 "..\..\Views\Category\CategoriesTemplate.cshtml"
                                                                                                                                                                                               Write(RootGlobalization.Button_Remove);

            
            #line default
            #line hidden
WriteLiteral("</a></div>\n        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" data-bind=\"attr: { name: getItemInputName($index()), value: id() }\"");

WriteLiteral(" />\n    </div>\n</div>\n");

        }
    }
}
#pragma warning restore 1591
