#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 28 "..\..\Views\Option\Partial\OptionCell.cshtml"
    using BetterCms.Module.Root;
    
    #line default
    #line hidden
    
    #line 29 "..\..\Views\Option\Partial\OptionCell.cshtml"
    using BetterCms.Module.Root.Mvc.Grids;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Option/Partial/OptionCell.cshtml")]
    public partial class _Views_Option_Partial_OptionCell_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Pages.Mvc.EditableGrid.OptionValueEditableGridColumn>
    {
        public _Views_Option_Partial_OptionCell_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\r\n");

WriteLiteral("\r\n<!-- ko if: !useDefaultValueBinding() && type() != 5 && type() != 4 && type() !" +
"= 21 && type() != 99 -->\r\n");

WriteLiteral("    ");

            
            #line 35 "..\..\Views\Option\Partial\OptionCell.cshtml"
Write(Html.Partial(RootModuleConstants.EditableGridCellTemplate));

            
            #line default
            #line hidden
WriteLiteral("\r\n<!-- /ko -->\r\n\r\n");

WriteLiteral("\r\n<!-- ko if: !useDefaultValueBinding() && type() == 21 -->\r\n");

WriteLiteral("    ");

            
            #line 40 "..\..\Views\Option\Partial\OptionCell.cshtml"
Write(Html.Partial(RootModuleConstants.EditableGridMultilineTextCellTemplate));

            
            #line default
            #line hidden
WriteLiteral("\r\n<!-- /ko -->\r\n\r\n");

WriteLiteral("\r\n<!-- ko if: !useDefaultValueBinding() && type() == 5  -->\r\n");

WriteLiteral("    ");

            
            #line 45 "..\..\Views\Option\Partial\OptionCell.cshtml"
Write(Html.Partial(RootModuleConstants.EditableGridBooleanCellTemplate, new EditableGridBooleanColumn(Model.HeaderTitle, Model.SortColumn, Model.ValueBind)
                                                                           {
                                                                               HiddenFieldName = Model.HiddenFieldName,
                                                                               HeaderAttributes = Model.HeaderAttributes,
                                                                               AutoFocus = Model.AutoFocus,
                                                                               CanBeEdited = Model.CanBeEdited,
                                                                               ShowValueAsText = true
                                                                           }));

            
            #line default
            #line hidden
WriteLiteral("\r\n<!-- /ko -->\r\n\r\n");

WriteLiteral("\r\n<!-- ko if: !useDefaultValueBinding() && type() == 4  -->\r\n<td ");

            
            #line 57 "..\..\Views\Option\Partial\OptionCell.cshtml"
Write(Html.Raw(Model.Attributes));

            
            #line default
            #line hidden
WriteLiteral(">\r\n");

            
            #line 58 "..\..\Views\Option\Partial\OptionCell.cshtml"
    
            
            #line default
            #line hidden
            
            #line 58 "..\..\Views\Option\Partial\OptionCell.cshtml"
     if (Model.CanBeEdited)
    {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"bcms-field-wrapper bcms-options-date\"");

WriteLiteral(" data-bind=\"visible: isActive()\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" class=\"bcms-field-text bcms-datepicker\"");

WriteLiteral(" data-bind=\"css: { \'bcms-input-validation-error\': !isNew() && ");

            
            #line 61 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                                                                                                        Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral(".hasError && ");

            
            #line 61 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                                                                                                                                       Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral(".hasError() }, value: ");

            
            #line 61 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                                                                                                                                                                               Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral(", valueUpdate: \'afterkeydown\', enterPress: onSave, escPress: onCancelEdit, afterR" +
"ender: initDatePickers(), visible: isActive() ");

            
            #line 61 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                                                                                                                                                                                                                                                                                                                                Write(!string.IsNullOrEmpty(Model.FocusIdentifier) ? string.Format(", hasfocus: {0}", Model.FocusIdentifier) : string.Empty);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("/>\r\n                <!-- ko if: !isNew() &&  ");

            
            #line 62 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                     Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral(".hasError && ");

            
            #line 62 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                                                    Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral(".hasError() -->\r\n                <span");

WriteLiteral(" class=\"bcms-field-validation-error\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" data-bind=\"html: ");

            
            #line 64 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                       Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral(".validationMessage()\"");

WriteLiteral("></span>\r\n                </span>\r\n                <!-- /ko -->\r\n            </di" +
"v>\r\n");

            
            #line 68 "..\..\Views\Option\Partial\OptionCell.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"bcms-tables-link\"");

WriteLiteral(" data-bind=\"text: ");

            
            #line 69 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                               Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral("() ");

            
            #line 69 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                                                    Write(!string.IsNullOrEmpty(Model.FocusIdentifier) ? string.Format(", click: onItemSelect.bind($data, {0})", Model.FocusIdentifier) : string.Empty);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 69 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                                                                                                                                                                                                    Write(Model.CanBeEdited ? ", visible: !isActive()" : string.Empty);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("></div>    \r\n</td>\r\n<!-- /ko -->\r\n\r\n");

WriteLiteral("\r\n<!-- ko if: !useDefaultValueBinding() && type() == 99  -->\r\n<td");

WriteLiteral(" class=\"bcms-table-field-helper\"");

WriteLiteral(" ");

            
            #line 75 "..\..\Views\Option\Partial\OptionCell.cshtml"
                               Write(Html.Raw(Model.Attributes));

            
            #line default
            #line hidden
WriteLiteral(">\r\n");

            
            #line 76 "..\..\Views\Option\Partial\OptionCell.cshtml"
    
            
            #line default
            #line hidden
            
            #line 76 "..\..\Views\Option\Partial\OptionCell.cshtml"
     if (Model.CanBeEdited)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"bcms-field-wrapper\"");

WriteLiteral(">\r\n        <input");

WriteLiteral(" class=\"bcms-field-text\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" readonly=\"readonly\"");

WriteLiteral(" data-bind=\"value: ");

            
            #line 79 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                                                                     Write(Model.CustomValueBind);

            
            #line default
            #line hidden
WriteLiteral("() || ");

            
            #line 79 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                                                                                                   Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral("(), enterPress: onSave, escPress: onCancelEdit,visible: isActive() ");

            
            #line 79 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                                                                                                                                                                                        Write(!string.IsNullOrEmpty(Model.FocusIdentifier) ? string.Format(", hasfocus: {0}", Model.FocusIdentifier) : string.Empty);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("/>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"bcms-btn-primary\"");

WriteLiteral(" data-bind=\"click: onCustomOptionExecute.bind($data, $data, ");

            
            #line 81 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                                                                             Write(Model.CustomValueBind);

            
            #line default
            #line hidden
WriteLiteral(", ");

            
            #line 81 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                                                                                                       Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral("), enterPress: onSave, escPress: onCancelEdit, visible: isActive()\"");

WriteLiteral(">...</div>\r\n");

            
            #line 82 "..\..\Views\Option\Partial\OptionCell.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"bcms-tables-link\"");

WriteLiteral(" data-bind=\" text: ");

            
            #line 83 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                                Write(Model.CustomValueBind);

            
            #line default
            #line hidden
WriteLiteral("() || ");

            
            #line 83 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                                                              Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral("() ");

            
            #line 83 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                                                                                   Write(!string.IsNullOrEmpty(Model.FocusIdentifier) ? string.Format(", click: onItemSelect.bind($data, {0})", Model.FocusIdentifier) : string.Empty);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 83 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                                                                                                                                                                                                                                   Write(Model.CanBeEdited ? ", visible: !isActive()" : string.Empty);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("></div>    \r\n</td>\r\n<!-- /ko -->\r\n\r\n");

WriteLiteral("\r\n<!-- ko if: useDefaultValueBinding() && type() == 5  -->\r\n");

WriteLiteral("    ");

            
            #line 89 "..\..\Views\Option\Partial\OptionCell.cshtml"
Write(Html.Partial(RootModuleConstants.EditableGridBooleanCellTemplate, new EditableGridBooleanColumn(null, null, Model.ValueBind) { CanBeEdited = false, ShowValueAsText = true }));

            
            #line default
            #line hidden
WriteLiteral("\r\n<!-- /ko -->\r\n\r\n<!-- ko if: useDefaultValueBinding() && type() != 5  -->\r\n<td ");

            
            #line 93 "..\..\Views\Option\Partial\OptionCell.cshtml"
Write(Html.Raw(Model.Attributes));

            
            #line default
            #line hidden
WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"bcms-tables-link\"");

WriteLiteral(" data-bind=\"text: ");

            
            #line 94 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                               Write(Model.CustomValueBind);

            
            #line default
            #line hidden
WriteLiteral("() || ");

            
            #line 94 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                                                             Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral("() ");

            
            #line 94 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                                                                                  Write(!string.IsNullOrEmpty(Model.FocusIdentifier) ? string.Format(", click: onItemSelect.bind($data, {0})", Model.FocusIdentifier): string.Empty);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("></div>\r\n</td>\r\n<!-- /ko -->\r\n");

        }
    }
}
#pragma warning restore 1591
