#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Option\Partial\OptionCell.cshtml"
    using BetterCms.Module.Root;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Option\Partial\OptionCell.cshtml"
    using BetterCms.Module.Root.Mvc.Grids;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Option/Partial/OptionCell.cshtml")]
    public partial class _Views_Option_Partial_OptionCell_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Pages.Mvc.EditableGrid.OptionValueEditableGridColumn>
    {
        public _Views_Option_Partial_OptionCell_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\n");

WriteLiteral("\n<!-- ko if: !useDefaultValueBinding() && type() != 5 && type() != 4 && type() !=" +
" 21 && type() != 99 -->\n");

WriteLiteral("    ");

            
            #line 8 "..\..\Views\Option\Partial\OptionCell.cshtml"
Write(Html.Partial(RootModuleConstants.EditableGridCellTemplate));

            
            #line default
            #line hidden
WriteLiteral("\n<!-- /ko -->\n\n");

WriteLiteral("\n<!-- ko if: !useDefaultValueBinding() && type() == 21 -->\n");

WriteLiteral("    ");

            
            #line 13 "..\..\Views\Option\Partial\OptionCell.cshtml"
Write(Html.Partial(RootModuleConstants.EditableGridMultilineTextCellTemplate));

            
            #line default
            #line hidden
WriteLiteral("\n<!-- /ko -->\n\n");

WriteLiteral("\n<!-- ko if: !useDefaultValueBinding() && type() == 5  -->\n");

WriteLiteral("    ");

            
            #line 18 "..\..\Views\Option\Partial\OptionCell.cshtml"
Write(Html.Partial(RootModuleConstants.EditableGridBooleanCellTemplate, new EditableGridBooleanColumn(Model.HeaderTitle, Model.SortColumn, Model.ValueBind)
                                                                           {
                                                                               HiddenFieldName = Model.HiddenFieldName,
                                                                               HeaderAttributes = Model.HeaderAttributes,
                                                                               AutoFocus = Model.AutoFocus,
                                                                               CanBeEdited = Model.CanBeEdited,
                                                                               ShowValueAsText = true
                                                                           }));

            
            #line default
            #line hidden
WriteLiteral("\n<!-- /ko -->\n\n");

WriteLiteral("\n<!-- ko if: !useDefaultValueBinding() && type() == 4  -->\n<td ");

            
            #line 30 "..\..\Views\Option\Partial\OptionCell.cshtml"
Write(Html.Raw(Model.Attributes));

            
            #line default
            #line hidden
WriteLiteral(">\n");

            
            #line 31 "..\..\Views\Option\Partial\OptionCell.cshtml"
    
            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\Option\Partial\OptionCell.cshtml"
     if (Model.CanBeEdited)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"bcms-input-list-holder\"");

WriteLiteral(">\n            <div");

WriteLiteral(" class=\"bcms-field-wrapper bcms-options-date\"");

WriteLiteral(" data-bind=\"visible: isActive()\"");

WriteLiteral(">\n                <input");

WriteLiteral(" class=\"bcms-field-text bcms-datepicker\"");

WriteLiteral(" data-bind=\"\n                    css: { \'bcms-input-validation-error\': !isNew() &" +
"& ");

            
            #line 36 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                                                  Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral(".hasError && ");

            
            #line 36 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                                                                                 Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral(".hasError() },\n                    value: ");

            
            #line 37 "..\..\Views\Option\Partial\OptionCell.cshtml"
                       Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral(",\n                    valueUpdate: \'afterkeydown\', \n                    enterPres" +
"s: onSave, \n                    escPress: onCancelEdit,\n                    afte" +
"rRender: initDatePickers(),\n                    visible: isActive()\n");

WriteLiteral("                    ");

            
            #line 43 "..\..\Views\Option\Partial\OptionCell.cshtml"
                Write(!string.IsNullOrEmpty(Model.FocusIdentifier) ? string.Format(", hasfocus: {0}", Model.FocusIdentifier) : string.Empty);

            
            #line default
            #line hidden
WriteLiteral("\n                       \"");

WriteLiteral(" />\n            \n                <!-- ko if: !isNew() &&  ");

            
            #line 46 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                     Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral(".hasError && ");

            
            #line 46 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                                                    Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral(".hasError() -->\n                <span");

WriteLiteral(" class=\"bcms-field-validation-error\"");

WriteLiteral(">\n                    <span");

WriteLiteral(" data-bind=\"html: ");

            
            #line 48 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                       Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral(".validationMessage()\"");

WriteLiteral("></span>\n                </span>\n                <!-- /ko -->\n            </div>\n" +
"        </div>\n");

            
            #line 53 "..\..\Views\Option\Partial\OptionCell.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <a");

WriteLiteral(" class=\"bcms-tables-link\"");

WriteLiteral(" data-bind=\"\n       text: ");

            
            #line 55 "..\..\Views\Option\Partial\OptionCell.cshtml"
         Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral("() ");

            
            #line 55 "..\..\Views\Option\Partial\OptionCell.cshtml"
                              Write(!string.IsNullOrEmpty(Model.FocusIdentifier) ? string.Format(", click: onItemSelect.bind($data, {0})", Model.FocusIdentifier) : string.Empty);

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("       ");

            
            #line 56 "..\..\Views\Option\Partial\OptionCell.cshtml"
   Write(Model.CanBeEdited ? ", visible: !isActive()" : string.Empty);

            
            #line default
            #line hidden
WriteLiteral("\n       \"");

WriteLiteral("></a>    \n\n</td>\n<!-- /ko -->\n\n");

WriteLiteral("\n<!-- ko if: !useDefaultValueBinding() && type() == 99  -->\n<td ");

            
            #line 64 "..\..\Views\Option\Partial\OptionCell.cshtml"
Write(Html.Raw(Model.Attributes));

            
            #line default
            #line hidden
WriteLiteral(">\n");

            
            #line 65 "..\..\Views\Option\Partial\OptionCell.cshtml"
    
            
            #line default
            #line hidden
            
            #line 65 "..\..\Views\Option\Partial\OptionCell.cshtml"
     if (Model.CanBeEdited)
    {

            
            #line default
            #line hidden
WriteLiteral("        <input");

WriteLiteral(" style=\"width: 70%\"");

WriteLiteral(" class=\"bcms-field-text\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" readonly=\"readonly\"");

WriteLiteral(" data-bind=\"value: ");

            
            #line 67 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                                                                                        Write(Model.CustomValueBind);

            
            #line default
            #line hidden
WriteLiteral("() || ");

            
            #line 67 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                                                                                                                      Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral("(), \n            enterPress: onSave, \n            escPress: onCancelEdit,\n       " +
"     visible: isActive()\n");

WriteLiteral("            ");

            
            #line 71 "..\..\Views\Option\Partial\OptionCell.cshtml"
        Write(!string.IsNullOrEmpty(Model.FocusIdentifier) ? string.Format(", hasfocus: {0}", Model.FocusIdentifier) : string.Empty);

            
            #line default
            #line hidden
WriteLiteral("\n               \"");

WriteLiteral(" />\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"bcms-btn-small\"");

WriteLiteral(" data-bind=\"\n                    click: onCustomOptionExecute.bind($data, $data, " +
"");

            
            #line 74 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                                                Write(Model.CustomValueBind);

            
            #line default
            #line hidden
WriteLiteral(", ");

            
            #line 74 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                                                                          Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral("),\n                    enterPress: onSave, \n                    escPress: onCance" +
"lEdit,\n                    visible: isActive()\"");

WriteLiteral(">...</div>\n");

            
            #line 78 "..\..\Views\Option\Partial\OptionCell.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <a");

WriteLiteral(" class=\"bcms-tables-link\"");

WriteLiteral(" data-bind=\"\n       text: ");

            
            #line 80 "..\..\Views\Option\Partial\OptionCell.cshtml"
         Write(Model.CustomValueBind);

            
            #line default
            #line hidden
WriteLiteral("() || ");

            
            #line 80 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                       Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral("() \n");

WriteLiteral("       ");

            
            #line 81 "..\..\Views\Option\Partial\OptionCell.cshtml"
   Write(!string.IsNullOrEmpty(Model.FocusIdentifier) ? string.Format(", click: onItemSelect.bind($data, {0})", Model.FocusIdentifier) : string.Empty);

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("       ");

            
            #line 82 "..\..\Views\Option\Partial\OptionCell.cshtml"
   Write(Model.CanBeEdited ? ", visible: !isActive()" : string.Empty);

            
            #line default
            #line hidden
WriteLiteral("\n       \"");

WriteLiteral("></a>    \n</td>\n<!-- /ko -->\n\n");

WriteLiteral("\n<!-- ko if: useDefaultValueBinding() && type() == 5  -->\n");

WriteLiteral("    ");

            
            #line 89 "..\..\Views\Option\Partial\OptionCell.cshtml"
Write(Html.Partial(RootModuleConstants.EditableGridBooleanCellTemplate, new EditableGridBooleanColumn(null, null, Model.ValueBind)
                                                                           {
                                                                               CanBeEdited = false,
                                                                               ShowValueAsText = true
                                                                           }));

            
            #line default
            #line hidden
WriteLiteral("\n<!-- /ko -->\n\n<!-- ko if: useDefaultValueBinding() && type() != 5  -->\n<td ");

            
            #line 97 "..\..\Views\Option\Partial\OptionCell.cshtml"
Write(Html.Raw(Model.Attributes));

            
            #line default
            #line hidden
WriteLiteral(">\n    <a");

WriteLiteral(" class=\"bcms-tables-link\"");

WriteLiteral(" data-bind=\"text: ");

            
            #line 98 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                             Write(Model.CustomValueBind);

            
            #line default
            #line hidden
WriteLiteral("() || ");

            
            #line 98 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                                                           Write(Model.ValueBind);

            
            #line default
            #line hidden
WriteLiteral("() ");

            
            #line 98 "..\..\Views\Option\Partial\OptionCell.cshtml"
                                                                                                Write(!string.IsNullOrEmpty(Model.FocusIdentifier) ? string.Format(", click: onItemSelect.bind($data, {0})", Model.FocusIdentifier): string.Empty);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("></a>\n</td>\n<!-- /ko -->\n");

        }
    }
}
#pragma warning restore 1591
