#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterCms.Module.Root.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/RootLayout.cshtml")]
    public partial class RootLayout : System.Web.Mvc.WebViewPage<dynamic>
    {
        public RootLayout()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\RootLayout.cshtml"
 if (IsSectionDefined("DoctypeTag"))
{
    
            
            #line default
            #line hidden
            
            #line 3 "..\..\Views\Shared\RootLayout.cshtml"
Write(RenderSection("DoctypeTag", false));

            
            #line default
            #line hidden
            
            #line 3 "..\..\Views\Shared\RootLayout.cshtml"
                                       
}
else {

            
            #line default
            #line hidden
WriteLiteral("    ");

WriteLiteral("<!DOCTYPE html>\r\n");

            
            #line 7 "..\..\Views\Shared\RootLayout.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 9 "..\..\Views\Shared\RootLayout.cshtml"
 if (IsSectionDefined("HtmlTag")) {
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Shared\RootLayout.cshtml"
Write(RenderSection("HtmlTag", false));

            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Shared\RootLayout.cshtml"
                                    
}
else {

            
            #line default
            #line hidden
WriteLiteral("    ");

WriteLiteral("<html>\r\n");

            
            #line 14 "..\..\Views\Shared\RootLayout.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("    <head>\r\n");

WriteLiteral("        ");

            
            #line 16 "..\..\Views\Shared\RootLayout.cshtml"
   Write(RenderSection("CmsMetaTitle", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 17 "..\..\Views\Shared\RootLayout.cshtml"
   Write(RenderSection("CmsMeta", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 18 "..\..\Views\Shared\RootLayout.cshtml"
   Write(RenderSection("CmsHeadStyles", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 19 "..\..\Views\Shared\RootLayout.cshtml"
   Write(RenderSection("CmsHeadScripts", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n        \r\n");

WriteLiteral("        ");

            
            #line 21 "..\..\Views\Shared\RootLayout.cshtml"
   Write(RenderSection("Styles", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 22 "..\..\Views\Shared\RootLayout.cshtml"
   Write(RenderSection("HeadScripts", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </head>\r\n");

            
            #line 24 "..\..\Views\Shared\RootLayout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\Shared\RootLayout.cshtml"
     if (IsSectionDefined("BodyTag"))
    {
        
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Shared\RootLayout.cshtml"
   Write(RenderSection("BodyTag", false));

            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Shared\RootLayout.cshtml"
                                        
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("<body ");

            
            #line 30 "..\..\Views\Shared\RootLayout.cshtml"
           Write(RenderSection("CmsBodyAttributes", false));

            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\Shared\RootLayout.cshtml"
                                                     Write(RenderSection("BodyAttributes", false));

            
            #line default
            #line hidden
WriteLiteral(">\r\n");

            
            #line 31 "..\..\Views\Shared\RootLayout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 32 "..\..\Views\Shared\RootLayout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 33 "..\..\Views\Shared\RootLayout.cshtml"
   Write(RenderSection("Scripts", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 34 "..\..\Views\Shared\RootLayout.cshtml"
   Write(RenderSection("CmsScripts", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
