#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterCms.Module.Root.Views.Category.Partial
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Category\Partial\CategoryTree.cshtml"
    using BetterCms.Module.Root.Content.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Category/Partial/CategoryTree.cshtml")]
    public partial class CategoryTree : System.Web.Mvc.WebViewPage<BetterCms.Module.Root.ViewModels.Category.CategoryTreeNodeViewModel>
    {
        public CategoryTree()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<!-- ko if: hasChildNodes() && showHasNoDataMessage() -->\r\n<div");

WriteLiteral(" class=\"bcms-nodes-dropzone bcms-nodes-dropzone-active\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"bcms-node-infotext\"");

WriteLiteral(">");

            
            #line 6 "..\..\Views\Category\Partial\CategoryTree.cshtml"
                               Write(RootGlobalization.Grid_NoDataAvailable_Message);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n</div>\r\n<!-- /ko -->\r\n<div");

WriteLiteral(" data-bind=\'template: { name: \"bcms-navigation-categorynode-template\" }\'");

WriteLiteral("></div>\r\n");

        }
    }
}
#pragma warning restore 1591
