#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 28 "..\..\Views\Page\Partial\PagesGrid.cshtml"
    using BetterCms.Module.Pages.Content.Resources;
    
    #line default
    #line hidden
    
    #line 29 "..\..\Views\Page\Partial\PagesGrid.cshtml"
    using BetterCms.Module.Root;
    
    #line default
    #line hidden
    
    #line 30 "..\..\Views\Page\Partial\PagesGrid.cshtml"
    using BetterCms.Module.Root.Content.Resources;
    
    #line default
    #line hidden
    
    #line 31 "..\..\Views\Page\Partial\PagesGrid.cshtml"
    using BetterCms.Module.Root.Mvc;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Page/Partial/PagesGrid.cshtml")]
    public partial class _Views_Page_Partial_PagesGrid_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Pages.ViewModels.Filter.PagesGridViewModel<BetterCms.Module.Pages.ViewModels.SiteSettings.SiteSettingPageViewModel>>
    {
        public _Views_Page_Partial_PagesGrid_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<div");

WriteLiteral(" id=\"bcms-pages-grid\"");

WriteLiteral(" class=\"bcms-list-pages\"");

WriteLiteral(">\r\n    <!-- ko foreach: items -->\r\n    <div");

WriteLiteral(" class=\"bcms-list-pages-row bcms-js-list-row\"");

WriteLiteral(" data-bind=\"click: onSelect, css: { \'bcms-list-row-active\': $parent.selectedRowId" +
"() == id() }\"");

WriteLiteral(">\r\n");

            
            #line 37 "..\..\Views\Page\Partial\PagesGrid.cshtml"
        
            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\Page\Partial\PagesGrid.cshtml"
         if ((ViewContext.Controller as CmsControllerBase).SecurityService.IsAuthorized(RootModuleConstants.UserRoles.MultipleRoles(RootModuleConstants.UserRoles.EditContent, RootModuleConstants.UserRoles.PublishContent)))
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"bcms-list-column bcms-list-edit\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"bcms-action-edit bcms-grid-item-edit-button bcms-js-edit-button\"");

WriteAttribute("title", Tuple.Create(" title=\"", 2231), Tuple.Create("\"", 2269)
            
            #line 40 "..\..\Views\Page\Partial\PagesGrid.cshtml"
                    , Tuple.Create(Tuple.Create("", 2239), Tuple.Create<System.Object, System.Int32>(RootGlobalization.Button_Edit
            
            #line default
            #line hidden
, 2239), false)
);

WriteLiteral(" data-bind=\"attr: { \'data-id\': id }, click: onEditClick\"");

WriteLiteral(">");

            
            #line 40 "..\..\Views\Page\Partial\PagesGrid.cshtml"
                                                                                                                                                                                       Write(RootGlobalization.Button_Edit);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            </div>\r\n");

            
            #line 42 "..\..\Views\Page\Partial\PagesGrid.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"bcms-list-column\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"bcms-list-link bcms-page-title\"");

WriteLiteral(" data-bind=\"text: title, attr: { \'data-url\': url, \'data-id\': id }, click: onTitle" +
"Click\"");

WriteLiteral("></div>\r\n\r\n            <div");

WriteLiteral(" class=\"bcms-list-row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"bcms-list-dates bcms-page-created\"");

WriteLiteral(" data-bind=\"text: createdOn\"");

WriteLiteral("></div>\r\n                <div");

WriteLiteral(" class=\"bcms-list-dates bcms-page-created\"");

WriteLiteral(" data-bind=\"text: modifiedOn\"");

WriteLiteral("></div>\r\n            </div>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"bcms-list-column bcms-list-status\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"bcms-page-ispublished\"");

WriteLiteral(" data-bind=\"attr: { class: pageStatus() == 3 ? \'bcms-action-ok\' : \'bcms-action-wa" +
"rn\', title: pageStatus() == 3 ? \'");

            
            #line 54 "..\..\Views\Page\Partial\PagesGrid.cshtml"
                                                                                                                                                           Write(PagesGlobalization.SiteSettings_PageStatus_Published);

            
            #line default
            #line hidden
WriteLiteral("\':\'");

            
            #line 54 "..\..\Views\Page\Partial\PagesGrid.cshtml"
                                                                                                                                                                                                                   Write(PagesGlobalization.SiteSettings_PageStatus_Unpublished);

            
            #line default
            #line hidden
WriteLiteral("\'}\"");

WriteLiteral("></div>\r\n        </div>\r\n\r\n");

            
            #line 57 "..\..\Views\Page\Partial\PagesGrid.cshtml"
        
            
            #line default
            #line hidden
            
            #line 57 "..\..\Views\Page\Partial\PagesGrid.cshtml"
         if ((ViewContext.Controller as CmsControllerBase).SecurityService.IsAuthorized(RootModuleConstants.UserRoles.DeleteContent))
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"bcms-list-column bcms-list-delete\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"bcms-action-delete bcms-grid-item-delete-button\"");

WriteAttribute("title", Tuple.Create(" title=\"", 3510), Tuple.Create("\"", 3550)
            
            #line 60 "..\..\Views\Page\Partial\PagesGrid.cshtml"
    , Tuple.Create(Tuple.Create("", 3518), Tuple.Create<System.Object, System.Int32>(RootGlobalization.Button_Delete
            
            #line default
            #line hidden
, 3518), false)
);

WriteLiteral(" data-bind=\"attr: { \'data-id\': id, \'data-version\': version }, click: onDeleteClic" +
"k\"");

WriteLiteral(">");

            
            #line 60 "..\..\Views\Page\Partial\PagesGrid.cshtml"
                                                                                                                                                                                                    Write(RootGlobalization.Button_Delete);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                <div");

WriteLiteral(" style=\"display: none\"");

WriteLiteral(" class=\"bcms-grid-item.message\"");

WriteLiteral("></div>\r\n            </div>\r\n");

            
            #line 63 "..\..\Views\Page\Partial\PagesGrid.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n    <!-- /ko -->\r\n    <!-- ko ifnot: items().length -->\r\n    <div");

WriteLiteral(" class=\"bcms-pages-no-data\"");

WriteLiteral(">No items to display</div>\r\n    <!-- /ko-->\r\n</div>");

        }
    }
}
#pragma warning restore 1591
