#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Page\Partial\TemplatesList.cshtml"
    using BetterCms.Module.Root.Content.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Page/Partial/TemplatesList.cshtml")]
    public partial class _Views_Page_Partial_TemplatesList_cshtml : System.Web.Mvc.WebViewPage<IList<BetterCms.Module.Pages.ViewModels.Page.TemplateViewModel>>
    {

#line 3 "..\..\Views\Page\Partial\TemplatesList.cshtml"
public System.Web.WebPages.HelperResult Templates(IList<BetterCms.Module.Pages.ViewModels.Page.TemplateViewModel> model)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 4 "..\..\Views\Page\Partial\TemplatesList.cshtml"
 
    if (model != null && model.Count > 0)
    {
        for (var i = 0; i < model.Count; i++)
        {
            

#line default
#line hidden

#line 9 "..\..\Views\Page\Partial\TemplatesList.cshtml"
WriteTo(__razor_helper_writer, Html.Partial("Partial/Template", model[i]));


#line default
#line hidden

#line 9 "..\..\Views\Page\Partial\TemplatesList.cshtml"
                                                       
        }
    }
    else
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <p>");


#line 14 "..\..\Views\Page\Partial\TemplatesList.cshtml"
WriteTo(__razor_helper_writer, Html.Raw(RootGlobalization.Message_NoItemToSelect));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</p>\r\n");


#line 15 "..\..\Views\Page\Partial\TemplatesList.cshtml"
    }


#line default
#line hidden
});

#line 16 "..\..\Views\Page\Partial\TemplatesList.cshtml"
}
#line default
#line hidden

        public _Views_Page_Partial_TemplatesList_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 17 "..\..\Views\Page\Partial\TemplatesList.cshtml"
  
    var active = Model.FirstOrDefault(m => m.IsActive);
    var selectFirstTab = active == null || !active.IsMasterPage;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"bcms-templates-holder\"");

WriteLiteral(">\r\n");

WriteLiteral("  ");

            
            #line 23 "..\..\Views\Page\Partial\TemplatesList.cshtml"
Write(Templates(Model.Where(m => !m.IsMasterPage).ToList()));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("  ");

            
            #line 24 "..\..\Views\Page\Partial\TemplatesList.cshtml"
Write(Templates(Model.Where(m => m.IsMasterPage).ToList()));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>");

        }
    }
}
#pragma warning restore 1591
