#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterCms.Module.Pages.Views.Page.Partial
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Page\Partial\TranslationsGrid.cshtml"
    using BetterCms.Module.Pages.Content.Resources;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Page\Partial\TranslationsGrid.cshtml"
    using BetterCms.Module.Root.Content.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Page/Partial/TranslationsGrid.cshtml")]
    public partial class TranslationsGrid : System.Web.Mvc.WebViewPage<dynamic>
    {
        public TranslationsGrid()
        {
        }
        public override void Execute()
        {


WriteLiteral("    \r\n<div data-bind=\"with: translations\" class=\"bcms-page-translations-content\">" +
"\r\n    <div class=\"bcms-add-language-button\">\r\n        <div class=\"bcms-btn-links" +
"-main\" data-bind=\"click: startEditMode\">");


            
            #line 6 "..\..\Views\Page\Partial\TranslationsGrid.cshtml"
                                                                     Write(PagesGlobalization.EditPageTranslations_AddTranslation_ButtonTitle);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n    </div>\r\n    \r\n    <table class=\"bcms-tables\">\r\n        <thead>\r\n     " +
"       <tr>\r\n                <th></th>\r\n                <th style=\"width: 350px;" +
"\">");


            
            #line 13 "..\..\Views\Page\Partial\TranslationsGrid.cshtml"
                                     Write(PagesGlobalization.EditPageTranslations_Title_Title);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                <th style=\"width: 250px;\">");


            
            #line 14 "..\..\Views\Page\Partial\TranslationsGrid.cshtml"
                                     Write(PagesGlobalization.EditPageTranslations_Language_Title);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                <th>");


            
            #line 15 "..\..\Views\Page\Partial\TranslationsGrid.cshtml"
               Write(PagesGlobalization.EditPageTranslations_Url_Title);

            
            #line default
            #line hidden
WriteLiteral(@"</th>
                <th class=""bcms-tables-nohover"" style=""width: 145px;"">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            
            <!-- ko foreach: items -->
            <tr>
                <td></td>
                <td data-bind=""html: title()""></td>
                <td data-bind=""html: languageName()""></td>
                <td><a data-bind=""html: url(), attr: {href: url()}"" target=""_blank""></a></td>
                <td>
                    <a class=""bcms-icn-delete"" data-bind=""click: $parent.unassignPage"">");


            
            #line 28 "..\..\Views\Page\Partial\TranslationsGrid.cshtml"
                                                                                  Write(RootGlobalization.Button_Delete);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                </td>\r\n            </tr>\r\n            <!-- /ko -->\r\n       " +
"     \r\n            <!-- ko if: items().length == 0 && !isInAddMode() -->\r\n      " +
"      <tr>\r\n                <td colspan=\"5\"><span class=\"bcms-table-no-data\">");


            
            #line 35 "..\..\Views\Page\Partial\TranslationsGrid.cshtml"
                                                            Write(RootGlobalization.Grid_NoDataAvailable_Message);

            
            #line default
            #line hidden
WriteLiteral(@"</span></td>
            </tr>
            <!-- /ko -->

            <!-- ko if: isInAddMode() -->
            <tr class=""bcms-table-row-active"">
                <td></td>
                <td>
                    <input  style=""width: 230px;"" type=""text"" class=""bcms-editor-field-box"" data-bind=""value: addPageTitle, autocomplete: 'onlyExisting', hasfocus: hasFocus, enterPress: addTranslation, escPress: endEditMode"" placeholder=""");


            
            #line 43 "..\..\Views\Page\Partial\TranslationsGrid.cshtml"
                                                                                                                                                                                                                                         Write(PagesGlobalization.EditPageProperties_TranslationsTab_PageSelectionPlaceholder);

            
            #line default
            #line hidden
WriteLiteral(@""" />
                    <div class=""bcms-btn-links-main"" data-bind=""click: selectPage"">BROWSE...</div>
                </td>
                <td colspan=""2"">
                    <!-- ko if: addPageId() && addingPageLanguages().length > 1 -->
                    <select style=""width: 100%;"" class=""bcms-global-select"" data-bind=""options: addingPageLanguages, optionsText: 'value', optionsValue: 'key', value: addLanguageId""></select>
                    <!-- /ko -->
                    <!-- ko if: addPageId() && addingPageLanguages().length == 1 -->
                    <span data-bind=""html: addingPageLanguages()[0].value""></span>
                    <!-- /ko -->
                </td>
                <td>
                    <!-- ko if: addLanguageId() -->
                    <div class=""bcms-btn-small"" data-bind=""click: addTranslation"">");


            
            #line 56 "..\..\Views\Page\Partial\TranslationsGrid.cshtml"
                                                                             Write(RootGlobalization.Button_Ok);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <!-- /ko -->\r\n                    <div class=\"bcms-bt" +
"n-links-small\" data-bind=\"click: endEditMode\">");


            
            #line 58 "..\..\Views\Page\Partial\TranslationsGrid.cshtml"
                                                                                Write(RootGlobalization.Button_Cancel);

            
            #line default
            #line hidden
WriteLiteral(@"</div>
                </td>
            </tr>
            <!-- /ko -->
        </tbody>
    </table>
</div>

<!-- ko foreach: translations.items -->
<input type=""hidden"" data-bind=""attr: { name: getPropertyIndexer($index(), 'LanguageId') }, value: languageId()"" />
<input type=""hidden"" data-bind=""attr: { name: getPropertyIndexer($index(), 'Id') }, value: id()"" />
<!-- /ko -->");


        }
    }
}
#pragma warning restore 1591
